### ISSUE TITLE
Issue with fractions in Word 2016

### ISSUE THREAD

**Issue by PeterHeidrich** [libertinus-fonts/libertinus#103]
In Word 2016, the setting of the equations seems to be okay.  When printed as PDF, the equations are no longer typset correctly.  An issue?  I used the revisions 6.4 and 6.5, both having the same issue?
Regards, Peter.
[test.docx](https://github.com/khaledhosny/libertinus/files/1433962/test.docx)
[test.pdf](https://github.com/khaledhosny/libertinus/files/1433963/test.pdf)

**Comment by KrasnayaPloshchad** [comment]
What happened if you print with PDFCreator?

**Comment by khaledhosny** [comment]
I can’t debug this, if onyone knows what is broken here, please send a pull request.
