### ISSUE TITLE
Add stylistic set to disable Th ligature or move it to a different ligature set

### ISSUE THREAD

**Issue by alerque** [libertinus-fonts/libertinus#104]
As recently [noted on Twitter](https://twitter.com/erajad/status/925774883941961728) some users (and [some other people](http://www.typophile.com/node/68486)) have a personal beef with the `Th` ligature. Some also [argue](https://english.stackexchange.com/a/55109/6807) it should be a decorative ligature instead of a standard one.

![](https://pbs.twimg.com/media/DNkQj0nX0AUGm_6.jpg)

I don't actually have a dog in this race, but it seems like either a way to disable this (perhaps a stylistic alternate that explicitly does not include it) or moving it to an optional decorative ligature set would be in order.

See also [this issue on EB Garamond](https://github.com/georgd/EB-Garamond/issues/34).

**Comment by KrasnayaPloshchad** [comment]
ZWNJ could be used to disable this.

**Comment by dajare** [comment]
Thanks for taking this on board. As mentioned in my Twitter post, the solution in [Linux Libertine Graphite][llg] was to add `lith` switch, so the font setting `Linux Libertine G:lith=1` would prevent the ligature:

![lith-switch-doc][01]

I suppose the **advantage** of that approach is that it does not require moving this ligature to another "set" -- as I understand it, this switch simply provides a specific over-ride. But I may not understand this quite correctly!

One **disadavantage** is that it creates a [non-standard feature switch][ot], although I don't know how serious this consideration is.

For the time being, inserting `U+2060` is a viable work around, although not ideal.

[01]: https://user-images.githubusercontent.com/40625/32365785-3589a498-c073-11e7-8c83-5a2b4b566d09.jpg "From the documentation for Linux Libertine Graphite"
[llg]: http://www.numbertext.org/linux/
[ot]: https://en.wikipedia.org/wiki/List_of_typographic_features

**Comment by khaledhosny** [comment]
`U+200C` is the proper Unicode way to prevent a ligature. But since I don’t like Th ligatures in general, I’m open to having a feature to disable it. I’m not going to use a non-standard tag though since this won’t work on applications that do not allow using feature tags directly. Using a stylistic set `ssXX` is a good compromise.

**Comment by KrasnayaPloshchad** [comment]
> Thanks for taking this on board. As mentioned in my Twitter post, the solution in Linux Libertine Graphite was to add lith switch, so the font setting Linux Libertine G:lith=1 would prevent the ligature:

Linux Libertine G is used Graphite layout to produce this feature, so such feature switch is available only in Graphite aware applications.

**Comment by KrasnayaPloshchad** [comment]
I think Th ligature can be moved to another ligature rules, but still available with `liga` feature: `T[ZWJ]h`.

**Comment by khaledhosny** [comment]
I opted to moving Th ligature to Discretionary Ligatures (`dlig`) feature, but also it can be enabled by explicitly inserting ZWJ between the two letters.
