### ISSUE TITLE
PDF not correctly produced with italics, old-style numbers and ligatures

### ISSUE THREAD

**Issue by PeterHeidrich** [libertinus-fonts/libertinus#109]
I tracked down an issue having annoyed me some time.  I prepared a Word 2016 document.  In Word 2016, everything seems to be okay.  However, the PDF output is seriously incorrect.  Files are annexed to this message.  I use the most recent set of fonts.
[Test_Lib_Serif_ligatures_kerning_oldstyle.pdf](https://github.com/khaledhosny/libertinus/files/1502860/Test_Lib_Serif_ligatures_kerning_oldstyle.pdf)
[Test_Lib_Serif_ligatures_kerning_oldstyle.docx](https://github.com/khaledhosny/libertinus/files/1502861/Test_Lib_Serif_ligatures_kerning_oldstyle.docx)

Regards,
Peter.

**Comment by khaledhosny** [comment]
Sorry, but I don’t know German. What are the names of these options in the English version of Word?

**Comment by nsemrau** [comment]
I made a quick 'n' dirty translation of the labels that are not equivalent in English:

![test_lib_serif_ligatures_kerning_oldstyle_english](https://user-images.githubusercontent.com/4363876/33457963-9b5113ee-d624-11e7-9306-2b9122fd7ec9.png)

**Comment by khaledhosny** [comment]
I have no idea how to debug this, if someone knows what is wrong please send a pull request.
