### ISSUE TITLE
Extra spacing between differential operator and variable of integration

### ISSUE THREAD

**Issue by jco2** [libertinus-fonts/libertinus#139]
I've noticed that there is too much space between a differential operator and a variable of integration in integrals. Here is an illustration :

![screenshot_20180314_210516](https://user-images.githubusercontent.com/29073309/37428393-6e1f73c6-27cc-11e8-9cd9-e4bf309aaa16.png)

The result is better when the 'd' is in normal font as can be seen with the first two d's :

![screenshot_20180314_211937](https://user-images.githubusercontent.com/29073309/37428735-7abf7ea4-27cd-11e8-9177-01a3643a6317.png)

The computer moder font doesn't have this problem :
![screenshot_20180314_212110](https://user-images.githubusercontent.com/29073309/37428859-daeaffd8-27cd-11e8-8681-103dff485b0d.png)

Is it feasible to adapt the spacing in this situation ?

**Comment by khaledhosny** [comment]
What application is this? I guess because our integrals are upright while Computer Modern’s are italic.

**Comment by jco2** [comment]
Hello and thank you for your prompt reply.
I don't think I was clear enough. I'm not talking about the spacing between the elongated 's' signs. Rather, I find the space between the 'd' and the letters v and w larger in Libertinus than in Computer Modern.
The examples are done with XeTeX.

**Comment by khaledhosny** [comment]
I see. I think this is a XeTeX bug with OpenType math fonts; looks like the italic correction is applied between `d` and `w`, but it shouldn’t since both are italic. Computer Modern is rendered with the old Math machinary that does not seem to have this bug.

**Comment by khaledhosny** [comment]
Or may be not, Computer Modern `d` has no italic correction, and the design of the glyphs seems to just give optimal spacing here. Kerning would have helped here, but unfortunately XeTeX does not support kerning for OpenType math fonts.

**Comment by KrasnayaPloshchad** [comment]
So is there anyway to report to XeTeX developer?

**Comment by krishnakumarg1984** [comment]
@khaledhosny  and @KrasnayaPloshchad  I don't think this is a XeTeX issue. I am using LuaTeX and I get the same issue. 

Do you think I should try by substituting a slanted integral from STIX TWO perhaps and see if the spacing improves?

**Comment by KrasnayaPloshchad** [comment]
Khaled, what happened if you add kernings for some mathematical italic letters?

**Comment by KrasnayaPloshchad** [comment]
Khaled, does LuaTeX really support kerning for OpenType math fonts? If so I guggest add some kernings for mathmetical letters.

**Comment by jco2** [comment]
@krishnakumarg1984 [this](https://tex.stackexchange.com/questions/23049/font-substitution-with-xelatex#23295) is what you need. You should then look at the [STIX 2 code chart](https://github.com/stipub/stixfonts/blob/master/docs/charts/StixTwoMath.pdf) to find the code point for the slanted integral.

**Comment by khaledhosny** [comment]
There is nothing to fix here. XeTeX and possibly LuaTeX are applying italic correction between `𝑑w` while they shouldn’t.
