### ISSUE TITLE
Implement more ligatures

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#143]
The following diagraphs and trigraphs marked in blue need to be implement ligatures. Actually it’s not hard work, the new glyph can be done by derivating existed glyphs.
![default](https://user-images.githubusercontent.com/10364351/37878300-6f6dd2a6-3099-11e8-8402-1b39091e07fa.PNG)
Note: the second section is showing discretionary ligatures, the _ij_ ligature in Linux Libertine G is available with Dutch locale.

**Comment by KrasnayaPloshchad** [comment]
Seen from [Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:Long_s), I think all of them can become ligature.

**Comment by moyogo** [comment]
I'd recommend breaking down those ligatures into components so they can be formed dynamically with contextual substitutions, for example f.beforetophook, f.beforeascender, f.beforesoftdot, etc.

**Comment by khaledhosny** [comment]
Agree with @moyogo (in case some one volunteers to do this, I’m not). Also `long s`+`s` needs to be kerned better, no ligature needed. The `c`+`k` and `c`+`h` ligatures does not make much sense other than in blackletter, so should actually be dropped.

**Comment by KrasnayaPloshchad** [comment]
@moyogo I agree with you, I found EB Garamond 12 produced ligatures in this way.

**Comment by skef** [comment]
Ligature support is now uniform across the main Serif faces. Which is not to say that all of the above have been added.
