### ISSUE TITLE
[Mono] Change default zero (0) to slashed or dotted

### ISSUE THREAD

**Issue by cssobral2013** [libertinus-fonts/libertinus#148]
This'll help programmers using this font.

**Comment by khaledhosny** [comment]
Feel free to send a pull request.

**Comment by cssobral2013** [comment]
It's SO BAD that a monospace font doesn't have a slashed or dotted zero, so
I decided to fork this font. Search on Google - corbi mono s font library.

Em qua, 3 de abr de 2019 05:54, Khaled Hosny <notifications@github.com>
escreveu:

**Comment by alerque** [comment]
@cssobral2013 Forking the font to add that feature isn't playing very nicely with open source. This project has specifically said it would accept a pull request. May I also suggest you add this character to the Libertinus Mono font and submit it here so that others from the wide installed base can benefit as well?

**Comment by waldyrious** [comment]
@khaledhosny I'd like to take this on, but I'm not sure how to proceed. Should I just replace the regular zero in the monospace font with the shape of the `zero.slash` character and remove the latter? Or should I keep the extra character to provide an alternate non-slashed zero (and posisbly rename it "non-slashed zero" or something like that)?

**Comment by khaledhosny** [comment]
I’m not convinced that the default should be slashed, as we already have `zero` feature for that and it would be a breaking change. I hope programmers aren’t actually using this font (I hope no one is really using it, I find it rather ugly).

**Comment by waldyrious** [comment]
Fair enough. I agree that the monospace font is not really usable, and that this change isn't particularly needed; I was looking at this issue mostly as a learning opportunity, to be honest.

Speaking of which, have you considered tagging some issues as "good first issue"? I see several that have been closed as "pull request welcome", such as this one, but it's not easy to locate those that a new contributor could look at to get started.

**Comment by khaledhosny** [comment]
Just if I had the hindsight to do this, but I’m not going through all these bugs to identify these, sorry. The wonfix bugs might be the closest to this collection.
