### ISSUE TITLE
Serbian dje has wrong form in Libertinus Serif Italic

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#153]
Serbian dje (ђ) looks like small _ᴛ_ in Libertinus Serif Italic.
![default](https://user-images.githubusercontent.com/10364351/38577122-a7528f2c-3d32-11e8-8a13-fd838c85171d.PNG)
See also:
http://sourceforge.net/p/linuxlibertine/bugs/170/
http://sourceforge.net/p/linuxlibertine/bugs/271/

**Comment by FloraCanou** [comment]
I'm sorry for being too late, but there are two more inconsistencies:
![default](https://user-images.githubusercontent.com/33727311/38668935-a7ab16ba-3e77-11e8-905b-835b8edc72c2.jpg)
They are Cyrillic small letter dje and Cyrillic small letter tshe
#145 #156 
To make things more tricky, glyphs with such a fork head also present in Regular font: Cyrillic small letter yat and Cyrillic small letter ka with stroke. These are consistent though

**Comment by KrasnayaPloshchad** [comment]
@FloraCanou I suggest adding `salt` feature for them.

**Comment by khaledhosny** [comment]
Duplicate of #246.

**Comment by khaledhosny** [comment]
Duplicate of #246
