### ISSUE TITLE
Restore Greek small caps

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#154]
SF.net having a request to add Greek small caps back in Libertine 5.3.0, where I saw a discussion at LaTeX Stack Exchange pointed to older version of Libertine font hosted at GitHub, so I think it’s possible to reintergrate Greek small caps in Libertinus Serif.

http://sourceforge.net/p/linuxlibertine/bugs/294/
https://tex.stackexchange.com/questions/75148/linux-libertine-does-not-show-greek-smallcaps

**Comment by khaledhosny** [comment]
Feel free to send a pull request.
