### ISSUE TITLE
Inconsistency in naming of some glyphs with diæresis?

### ISSUE THREAD

**Issue by mgavioli** [libertinus-fonts/libertinus#162]
**Situation**:
While revising the diacritics / anchor situation (currently for Serif Regular), I noticed that the 3 glyphs Ä (U+00C4), Ö (U+00D6), Ü (U+00DC) have unusual names: `Adieresis.alt`, `Odieresis.alt` and `Udieresis.alt` respectively.

They also bear a comment in German which, translated to English sounds like: ”These are alternative umlauts which are preferable in German".

The font also has glyphs named `Adieresis`, `Odieresis` and `Udieresis` (without `.alt`) in the unencoded slots:

![issue_aoudieresis](https://user-images.githubusercontent.com/1420743/38801144-55f1b35c-4169-11e8-8af9-12d42a6e3f94.png)

To my eye, the `.alt` glyphs look totally normal, while the non-`.alt` version look 'stylized' and I remember similar shapes -- with more 'embedded' umlauts -- in German publications from the early-to-middle XX century.

The `.alt` forms (with Unicode encoding) are the ones shown by, for instance, LibreOffice without any special command or formatting (in any language I tried, including, but not limited to, German):

Finally, the `ss01` style set turns the `.alt` forms into the non-`.alt` forms (but not vice versa).

The Italic shows the same setup; I have not checked the other fonts, but two fonts are enough to tell this was intentional (at least in origin).

**Issue**:
This probably does not creates problems to the final user, but it breaks the automatic generation of accented glyphs (`Adieresis` references the `A.alt` glyph as base, rather than `A`) and will surely puzzle any future maintainer of the font(s).

**Suggestion**:
Move the `.alt` suffix from the names of the 'regular' glyphs (the top 3 in the image) to the names of the 'stylized' ones (the bottom 3), adapting the names in the `ss01` set.

I see no side effects in this; if accepted, I can include this in the forthcoming PR with updated anchor system.

**Comment by khaledhosny** [comment]
See #2 and 467d782d67705560ba3ebcfa23d2698df1ca747f for background. I simply changed the encoding without renaming the glyphs as I had bad experience renaming glyphs in FontForge in the past (kerning classes not being updated, renaming `foo` glyph to `foo.bar` renames all `foo.*` glyphs to `foo.bar.*`, and may be more). The `ss01` feature is used to map from the encoding to the unencoded version).

**Comment by mgavioli** [comment]
OK; I still believe the names should be fixed. Thanks for the head-up about glyph renaming; perhaps it is better to have a separate PR for easier check of side effects, maybe later down the road.

**Comment by khaledhosny** [comment]
Sure, I’m not opposed to fixing the names.
