### ISSUE TITLE
No kerning for crossed W alternate glyph

### ISSUE THREAD

**Issue by Eisfunke** [libertinus-fonts/libertinus#163]
When trying out the crossed W alternate glyph (available as OpenType feature `ss05`), I noticed that it seems to have no kerning:

![crossed](https://user-images.githubusercontent.com/18213227/38991464-3470e55a-43de-11e8-98fe-cf306ee7a6af.png)

You can try it out with the following LaTeX (use XeLaTeX or LuaLaTeX):
```
\documentclass[paper=a4, parindent=0pt, parskip=half]{scrartcl}

\usepackage{fontspec}
\setmainfont{Libertinus Serif}

\begin{document}
    \Huge
    Wo
    \addfontfeatures{StylisticSet = 5}\\
    Wo
\end{document}
```

Not that it's important, but is there any chance the kerning could be added?

**Comment by KrasnayaPloshchad** [comment]
The kerning can be added via port some kerning data from default glyph.

**Comment by Eisfunke** [comment]
This is great, thank you!
