### ISSUE TITLE
Resizing some math symbols

### ISSUE THREAD

**Issue by jabirali** [libertinus-fonts/libertinus#164]
First of all, thanks for the great work on the Libertinus font family! :)

Lately, I've been trying to adopt it for my PhD thesis, but have run into some issues with the kind of equations that usually pop up in my field. I therefore thought I'd bring it up here, and see if you'd be open to either changing some default symbols, or at least adding some stylistic alternates.

In physics, it's quite common to use a superscript asterisk and dagger to denote complex conjugation and Hermitian conjugation, respectively. For this use, I believe that the dagger provided by Libertine Math is way too large, while the asterisk is too small. It is also common to use subscript arrows to denote the quantum spin of particles; and in my opinion, the default arrows in Libertine Math are too tall for this use.

To illustrate the typographic issue, here are some typical equations from condensed matter physics, rendered using the newest version of Libertinus Math (via lualatex and unicode-math):

![original_](https://user-images.githubusercontent.com/271284/39101247-4ad0ac34-4697-11e8-8dd3-94f534885d72.png)
Ideally, I think all the subscripts and superscripts in these equations should be of roughly the same size; e.g. in Δs* the asterisk should be the same size as an s, in general a dagger and asterisk should have similar sizes since they have similar uses, and the arrows should not be larger than the symbol they're attached to. The size disparity between the asterisk and dagger might be an issue for Libertinus Serif as well as Libertinus Math, since they are frequently used in the same contexts as e.g. footnote marks. To summarize, this is what I think it should look like (here using a dagger from Warnock Pro, an asterisk from TeX Gyre Pagella Math, and arrows that I vertically shortened myself in FontForge):

![fixed__](https://user-images.githubusercontent.com/271284/39101326-57e127ae-4698-11e8-977b-1a7c39b969ce.png)

For comparison, this is how the same code is rendered by STIX 2.0 (with stylistic set 5 enabled):
![stix2_](https://user-images.githubusercontent.com/271284/39101250-542e8490-4697-11e8-9e93-31902023c6f7.png)

I am by no means a type designer, so it would probably be ideal if someone with more experience could look into this... But if not, I could give it a try myself if you'd be willing to merge such changes :).

**Comment by khaledhosny** [comment]
I generally agree that many math symbol sizes are less than ideal, see #63 also. I’m open to merging any contribution towards this, otherwise I’ll get to it eventually.
