### ISSUE TITLE
Misplaced combining acute accent U+0301 on Cyrillic letters

### ISSUE THREAD

**Issue by eg9** [libertinus-fonts/libertinus#17]
The combining acute accent U+0301 is misplaced on Cyrillic uppercase vowels and on wide lowercase ones.

The bug is also on legacy Linux Libertine fonts.

Example file

```
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Libertinus Serif}
\setsansfont{Libertinus Sans}

\newcommand\CyrillicAccents{А а А́ а́ \\ Е е Е́ е́ \\ И и И́ и́ \\ О о О́ о́ \\
  У у У́ у́ \\ Ы ы Ы́ ы́ \\ Э э Э́ э́ \\ Ю ю Ю́ ю́ \\ Я я Я́ я́}

\begin{document}

\parbox[t]{3cm}{\CyrillicAccents}
\parbox[t]{3cm}{\sffamily\CyrillicAccents}

\end{document}
```

Reference: http://tex.stackexchange.com/questions/199080/misplaced-accents-in-cyrillic-text

Output

![screen shot 2016-02-01 at 14 01 10](https://cloud.githubusercontent.com/assets/302839/12718147/cd87702a-c8ec-11e5-8fbd-c1fbb39de91b.png)

**Comment by khaledhosny** [comment]
Looks like almost all Cyrillic glyphs lack anchors for accent positioning, it can be fixed but it is a laborious task so will take a while (let me know if you want to help and can get FontForge running on your system, I’ve some ideas that would allow something familiar with Cyrillic to help without needing much experience with font development).

**Comment by KrasnayaPloshchad** [comment]
This bug also affect letter С́, which is recommended for Montenegrin.

**Comment by landswellsong** [comment]
@KrasnayaPloshchad does it affect З́?

**Comment by KrasnayaPloshchad** [comment]
Yes.

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
