### ISSUE TITLE
Documentation of Libertinus's open type features?

### ISSUE THREAD

**Issue by JakobWerner** [libertinus-fonts/libertinus#173]
Maybe I just didn't search correctly, but I couldn't find a place where Libertinus's open type features, ligatures, stylistic sets, … are documented for the end user. Maybe a documentation (e.g. in the style of `texdoc junicode`) could be added? I would be willing to contribute one myself, but unfortunately I don't know about the available features myself, and also I don't think I could produce such a neat document.

**Comment by khaledhosny** [comment]
We don’t currently have any user documentation, unfortunately. Some features are documented in the old Linux Libertine website: http://libertine-fonts.org/, and the definite list of features supported by each font can be obtained by `otfinfo`. If someone can contribute some user documentation, that’d be highly appreciated. I can answer any questions and help review it.

**Comment by RGB-es** [comment]
I wrote a quick review for my blog (not sure if it's right to put a link to it here). As Khaled said, at least on Linux you can use 

`otfinfo -f libertinusserif-regular.otf`

to get a list of OT tags available and then just use a recent version of LibreOffice to test those features (or document them!). To test Libertinus Math you need to use XeTeX, though (I wrote about that, too...).

**Comment by khaledhosny** [comment]
I moved the repository to its own organization for better organization (pun intented), and we now have a empty GitHub pages repository: https://github.com/libertinus-fonts/libertinus-fonts.github.io, in case someone wants to populate it with some useful documentation pages.

**Comment by waldyrious** [comment]
> Some features are documented in the old Linux Libertine website: http://libertine-fonts.org

For reference, the latest archive.org snapshot of the old website at linuxlibertine.org is from [2017-10-14](http://web.archive.org/web/20171014200644/http://www.linuxlibertine.org:80/index.php?id=1&L=1).

**Comment by KrasnayaPloshchad** [comment]
The following archive is good to be reference:
https://web.archive.org/web/*/http://www.linuxlibertine.org:80/fileadmin/user_upload/PDF/Libertine-XeTex-EN.pdf

**Comment by gyuris** [comment]
Can you document '[nalt](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#a-namenalt-idnaltatag-nalt)' feature, please? I see in the source (①-⑳) and with `otfinfo` but  I can't use it.

**Comment by kenmcd** [comment]
The **nalt** feature does not seem to work how you would expect.  
You think it is going to take these three characters "(1)" and convert it to ① (U2460).
But what it does is take ⑴ (U2474, Parenthesized Digit 1) and convert it to ① (U2460).

There is no conversion of the characters "(1)" into ⑴ (U2474) or ① (U2460) in the font file that I can see.
Seems kinda pointless if you have to enter Unicode anyway.
I checked Linux Libertine G and it works the same way.

I too have been working on OpenType documentation for LibreOffice which includes Libertinus.
The only font I have found to demo Enclosed Alphanumerics is actually using Ornaments.

Saw the call for documentation and am now also working on some docs for the Libertinus font family.

**Comment by gyuris** [comment]
@kenmcd, thanks for you answer. Meanwhile I found how this feature works and I documented it in referenced pull request #182. See the documents there. It you have found any further non documented feature, please do not hesitate to contact. Where is your OpenType documentation for LibreOffice?

About `nalt` in [Linux Libertine G graphite font feature](http://www.numbertext.org/linux/fontfeatures.pdf): Yes, [nemeth](https://github.com/laszlonemeth) implemented the standard `nalt` feature, but there is an another extra `circ` feature to convert 1 to U2460 or U2474 or 24DB or 2776. This `circ` feature is very useful in LibreOffice for automatic numbering.

**Comment by kenmcd** [comment]
Hmmm ... circ is not an OpenType feature.
Which explains why it did not show up when I was examining the font in the FontCreator OpenType tool.
On my phone now; will look at circ later on PC.

The LO OpenType guide is a part of an LO Fonts Guide I have been working on. Scope creep and other factors have delayed it. It may become part of a larger doc.

Think I will do a much smaller Libertinus fonts guide first. Something I can actually finish in a reasonable time frame, and many elements will be the same set-up and can be reused.

**Comment by kenmcd** [comment]
@gyuris,
I tested the `circ` feature - that only works in a Graphite font - e.g. Linux Libertine G.
Does not work in Libertinus Serif when I tested.
I dumped the Libertinus Serif font file to XML with TTX and scanned it - nothing in there for `circ`.
So it appears that the Graphite stuff was removed and the `nalt` is either orphaned or incomplete.

To do this properly there is going to need to be a lookup table like for ligatures and fractions.
I did find a commercial font from FontFont which has implemented Enclosed Alphanumerics using the `aalt` feature - Access All Alternates.
Have not been able to get my hands on the actual font yet to see exactly what they did.

Could also be done as ligatures or stylistic sets.
To me stylistic sets makes the most sense.
Four sets and a ligature lookup table would work.

**Comment by kenmcd** [comment]
@gyuris,
I tested the `circ` feature - that only works in a Graphite font - e.g. Linux Libertine G.
Does not work in Libertinus Serif when I tested.
I dumped the Libertinus Serif font file to XML with TTX and scanned it - nothing in there for `circ`.
So it appears that the Graphite stuff was removed and the `nalt` is either orphaned or incomplete.

To do this properly there is going to need to be a lookup table like for ligatures and fractions.
I did find a commercial font from FontFont which has implemented Enclosed Alphanumerics using the `nalt` feature.
Have not been able to get my hands on the actual font yet to see exactly what they did.

Could also be done as ligatures or stylistic sets.
To me stylistic sets makes the most sense.
Four sets and a ligature lookup table would work.

**Comment by khaledhosny** [comment]
>  So it appears that the Graphite stuff was removed

Graphite version is an independent fork of Linux Libertine, it was never merged upstream:
https://numbertext.org/linux/

**Comment by KrasnayaPloshchad** [comment]
@gyuris I suggest open a new issue for this.

**Comment by gyuris** [comment]
OK. `circ` is a non OpenType feature, it is a [Graphite](https://en.wikipedia.org/wiki/Graphite_(SIL)) feature in [Linux Libertine G](http://www.numbertext.org/linux/fontfeatures.pdf) fork. This issue is about documenting current Libertinus OpenType features. I split Graphite technology topic in another issue: #184.

**Comment by nsemrau** [comment]
Sorry to chime in this late, but I've overlooked `-calt`s caption, which reads "Contextual Alternates (d**a**fault)".

**Comment by khaledhosny** [comment]
> Sorry to chime in this late, but I've overlooked `-calt`s caption, which reads "Contextual Alternates (d**a**fault)".

Fixed it, thanks!
