### ISSUE TITLE
Add Yod traingle sign

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#179]
Unicode 11 is planned to add Yod traingle sign in Hebrew block (U+05EF), but that is not so hard work in Libertinus Serif, you can do it in the following steps: first, copying glyph reference from Yod, second, paste it three times into new codepoint, finally, adjust their position.

**Comment by KrasnayaPloshchad** [comment]
On Wikipedia article [Hebrew (Unicode block)](https://en.wikipedia.org/wiki/Hebrew_(Unicode_block)) I saw 6 documentations about the historical usage of this sign.

**Comment by khaledhosny** [comment]
Feel free to send a pull request.
