### ISSUE TITLE
Add small captial Q

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#180]
Unicode 11 is planned to add small capital q in U+A7AF.

**Comment by KrasnayaPloshchad** [comment]
I remembered Linux Libertine 5.3.0 has small captial Q, but it was encoded in PUA, so I think you can import into Libertinus and re-encode it.

**Comment by moyogo** [comment]
`q.sc` cannot be used for U+A7AF because it’s too large. See for example how `n.sc` is not the same as uni0274.

**Comment by KrasnayaPloshchad** [comment]
So I think this can be achieved via copying glyph reference from q.sc.
________________________________
发件人: Denis Moyogo Jacquerye <notifications@github.com>
发送时间: 2018年6月18日 16:11:21
收件人: libertinus-fonts/libertinus
抄送: Krasnaya Ploshchad’; Author
主题: Re: [libertinus-fonts/libertinus] Add small captial Q (#180)


q.sc cannot be used for U+A7AF because it’s too large. See for example how n.sc is not the same as uni0274.

―

**Comment by KrasnayaPloshchad** [comment]
Oh, that’s weird, so we have to redesign some small capital letters for design consistency.

**Comment by khaledhosny** [comment]
Feel free to send a pull request.
