### ISSUE TITLE
Multiple combining diacritics placement

### ISSUE THREAD

**Issue by Ad-Astm** [libertinus-fonts/libertinus#181]
Hello,

For the transliteration (Romanisation) of Gandhari I am coming across some diacritic combinations which are needed but which do not align properly with each other and/or with their base character in Libertinus fonts. The issues are as follows:

- s-undermacron combined with underdot … undermacron is not centred properly … in serif the two diacritics overlap
- g-undermacron … macron is not below bowl
- s-ovemacron combined with acute accent … diacritics overlap
- t underdot with acute accent above …. accent touches base character, may be the 

I was just wondering, when issues are resolved is the download automatically updated or do we have to wait for the next release?

Thank you,

**Comment by khaledhosny** [comment]
Please provide the actual text strings (or Unicode code points) for easier testing.

**Comment by Ad-Astm** [comment]
- d-underdot combined with undermacron ... i.e. u1E0D + u0331
- g-undermacron … i.e. u0067+ u0331
- s-ovemacron combined with acute accent … i.e. u015B + u0304
- s-underdot combined with undermacron … i.e. u1E63 + u0331
- t-underdot with acute accent above …. i.e. u1E6D + u0301

I uncovered these problems using Libertinus Sans. I have not extensively tested other Libertinus typefaces and glyph combinations.

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
