### ISSUE TITLE
Port best non standard Graphite features from Linux Libertine G fork

### ISSUE THREAD

**Issue by gyuris** [libertinus-fonts/libertinus#184]
As end user I think there are some very useful feature in [Linux Libertine G](http://www.numbertext.org/linux/) font, which will be nice to port here as OpenType features. I know that [Graphite](https://en.wikipedia.org/wiki/Graphite_(SIL)) is more flexible technology, so my question is: Is it possible to implement these features in OpenType so useful as in Linux Libertine G (with ssXX or with some other feature)?

I think the most useful features are these, see in [documentation](http://www.numbertext.org/linux/fontfeatures.pdf):

1. `dbls`: Replace latin capital letters with double-stroke glyphs. It is simple and useful for headings or initials.
![linux libertine g graphite dbls](https://user-images.githubusercontent.com/847982/40408931-85196c48-5e69-11e8-806b-2db1c77b6fb8.png)
2. `circ`: Replace normal numbers with other number glyps. It is very useful for automatic numbering or in legal texts. In Linux Libertine G there are 4 variant to replace normal arabic numerals (1-20 or double circled to 10). I think we can extend this to replace roman numerals with real latin numeral glyphs (1-12) too.
![linux libertine g graphite circ](https://user-images.githubusercontent.com/847982/40408949-949ec56e-5e69-11e8-9c6a-4a59fb244937.png)

Currently we have `nalt` in Libertinus, but it is not useful. Why to replace U2474 (1 with paranthesis)  to U2460 (1 circled)?

We have some many good glyphs in Libertinus font, we just need to invoke them. So, is it possible with OpenType?

**Comment by kenmcd** [comment]
I am going to work on this today.
I found another font which used `nalt` to replace `0-9, A-Z, a-z` with circled versions (e.g. ① etc.).
That is just a straight single replacement.
So I am going to plug that into Libertinus Serif Regular today.

The other sequences which have numbers above 0-9 will require replacing multiple characters like is done for ligatures and fractions.
For example these three characters `(1)` could be mapped to ⑴ (U2474).
And that way `(12)` could be mapped to ⑫, or ⑿, or ⓬, or Ⅻ, or ⅻ.
Those will probably be best as Stylistic Sets.
Thoughts?

**Comment by kenmcd** [comment]
Already added all the `nalt` characters for `0-9, A-Z, a-z`. Works fine.
The characters are actually named `0.nalt`, `A.nalt`, `a.nalt`, etc.
Appears that is what they are for.

The whole point of OpenType user features is to make it easier to access the thousands of characters.
Why not just type nothing but character codes all the time? 
That's a stupid argument.

Was in the middle of adding the other sets, when I saw this.
If you have no interest in adding useful features I will just drop this.

**Comment by khaledhosny** [comment]
>  The characters are actually named `0.nalt`, `A.nalt`, `a.nalt`, etc.

Glyph names do not really matter, what matter is whether they directly map to characters (AKA encoded) or not.

> The whole point of OpenType user features is to make it easier to access the thousands of characters.

No, that is not even one of its purposes. Furthermore, OpenType operates on glyphs not characters. If one wants a given character, the only canonical way to get it is to input the said characters. Mapping other characters to ASCII though OpenType is at best a hack, and one that I strongly prefer not to have.

I appreciate your any anyone else’s contribution, sincerity and I do not wish to upset anyone. But there is a lot of bugs and misfeatures in these fonts right now and I’m trying, with everyone’s help, to clean this up.

**Comment by kenmcd** [comment]
I know the difference between a character and a glyph.
But that is irrelevant.
Typical LibreOffice-style focus on nonsense.

Clearly it is a waste of time trying to add enhanced features to these fonts.
I guess those idiots at Adobe, FontFont, and Linotype just do not understand the technical aspects.
At least their clueless users in the graphic design industries get some great features/mistakes to help them do their daily work.

I give. You win.
Off to do something productive.

**Comment by gyuris** [comment]
@khaledhosny, I understood your point.

**Comment by khaledhosny** [comment]
@kenmcd Thanks for your interest, though. Fortunately you can still fork the fonts and do the changes you need.

**Comment by kenmcd** [comment]
Yes, I thought of that last night.
Was just going to drop Libertinus from the docs in-progress, but realized I can fork and rename it.
So I do not have to waste all that work.
And users will get more usable OpenType features and good documentation on how to use them.
