### ISSUE TITLE
"case" font feature

### ISSUE THREAD

**Issue by ArTourter** [libertinus-fonts/libertinus#185]
Hi,
the documentation describes the case feature as being "Case-Sensitive Forms". however, with both lualatex and xelatex, that feature uses the uppercase forms inrespective of the case of the surrounding glyphs.

Is that the expected behaviour?

To me, if it were case-sensitive, the - in CD-ROM and cd-rom should be different with the feature turned on. I guess the issue then is which form to use in a mixed case environment (e.g., Blu-Ray)

Thanks

**Comment by khaledhosny** [comment]
>  By the way, the document you link to also mentions that is should also change oldstyle to lining figures.

Libertinus does not currently do that, and I’m not sure if it should, what if someone wanted oldstyle figures while case is active? (not that I can think of a reason why one would want that). Better keep things simple.
