### ISSUE TITLE
Small Caps version of Fonts?

### ISSUE THREAD

**Issue by dbhertz** [libertinus-fonts/libertinus#186]
This may be a naive question, but I was wondering whether there was a way of generating the fonts with specific otf features permanently turned on. Specifically, there are a number of applications (like Word, Excel, etc.) that don't fully support otf features (small caps specifically), and I was hoping to be able to make a small caps version of the fonts to use for those.
I know that one response to this is simply not to use applications that don't properly support otf features; that's unfortunately not an option for me.

**Comment by khaledhosny** [comment]
See https://github.com/libertinus-fonts/libertinus/issues/43#issuecomment-247726083.
