### ISSUE TITLE
Diacritic placement (Libertinus serif)

### ISSUE THREAD

**Issue by Ad-Astm** [libertinus-fonts/libertinus#187]
Similar to issue #181, please see image below in which the underdot is not placed in the ideal position with respect to the base glyph for italic m, r, and v. This is both for the glyphs which have the underdot and when the base glyph is used and then the combining underdot is used as a separate glyph.

In addition, see how the macron or tilde is not place correctly in the last 3 italic glyphs.

For u-diaresis-macron-above (italic) the macron is almost touching the diaresis. For the regular version of the glyph the vertical spacing between the base glyph and diaresis is even.

For U-diaresis and O-diaresis the macron/tilde is not centred between the 2 dots.

رمضان کریم و جزاکم الله خیر الجزاء

![image](https://user-images.githubusercontent.com/27583305/40673154-d628c01c-6368-11e8-905a-bef1fdd68713.png)

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
