### ISSUE TITLE
Missing super/subscripts - Issues with realscripts package

### ISSUE THREAD

**Issue by Doc73** [libertinus-fonts/libertinus#191]
I would suggest to add, if possible, superscripts and subscripts for Italic and Bold/BoldItalic, to be able to use `realscripts` package.

It would be greatly appreciated.

Many thanks in advance,
Domenico

P. S.: I can add a MWE, if needed.

**Comment by Doc73** [comment]
I did some tests and noticed that this issue is related to `osf` option. Here is a MWE, from which we deduce that the original Linux Libertine O font is not affected by this issue.

```tex
% !TeX program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT

\documentclass[a4paper]{book}
\usepackage{fontspec}
\setmainfont[Ligatures=TeX,Numbers=OldStyle]{Libertinus Serif}
%\setmainfont[Ligatures=TeX]{Libertinus Serif}
\newfontfamily\libertine{Linux Libertine O}
\usepackage{realscripts}

\begin{document}
\section{Libertinus Serif}
A\textsuperscript{0123456789}

\textit{A\textsuperscript{0123456789}}

\textbf{A\textsuperscript{0123456789}}

\section{Linux Libertine O}
\libertine{
A\textsuperscript{0123456789}

\textit{A\textsuperscript{0123456789}}

\textbf{A\textsuperscript{0123456789}}
	}
\end{document}
```

**Comment by khaledhosny** [comment]
I see. So we don’t have old style superscripts, and Linux Libertine was always using lining figures for superscripts. Would this be an acceptable solution?

**Comment by Doc73** [comment]
Excellent solution for me! I'd prefer lining figures for both super and subscripts.

**Comment by skef** [comment]
`sinf` and `sups` now supersede `onum` in all the main fonts.
