### ISSUE TITLE
\coloneqq has the colon too close to the equal sign.

### ISSUE THREAD

**Issue by MathStudent999** [libertinus-fonts/libertinus#192]
Hello,
While I was writing an equality by definition, I noticed the \coloneqq is almost indistinguishable from a regular equal sign since the the colon is too close.

![screenshot_2018-06-23_01-33-44](https://user-images.githubusercontent.com/40512647/41806142-39e4b6bc-7686-11e8-8cbd-2f27815e4d25.png)

**Comment by krishnakumarg1984** [comment]
I have this identical problem for my phd thesis. When will this fix be available?

**Comment by alerque** [comment]
@krishnakumarg1984 This fix already _IS_ available. The commit that closed this issue has the rebuilt font file. If you use font from the latest files in the repository this should be fixed.

**Comment by khaledhosny** [comment]
No set date for the next release yet as I have few things that I need to fix before the release. But as @alerque said, releasing does not mean it will be picked automatically by, say, TeX Live, as I'll also need to upload the release to CTAN, wait for it to be published, then wait for TeX Live team to pick it up.
