### ISSUE TITLE
Stylistic alternate for the letters d and u

### ISSUE THREAD

**Issue by kauesena** [libertinus-fonts/libertinus#194]
Sometimes the bottom extremity of the vertical stroke of the letters "d" and "u" is distracting during reading. When the font size is small and one is reading on a computer screen, the "serif" seems like some bug, some rendering problem. When one is reading it on paper, depending on the conditions of printing and the font size, it may seem like a printing error. Maybe it just bugs me, but I think that it probably annoys other people so that an stylistic alternate for those characters with a flat end would be nice. The second line of the following image illustrates what I suggest as an alternate, it is from Utopia font.

![screenshot from 2018-06-24 10-27-09](https://user-images.githubusercontent.com/30255100/41819591-2ff751dc-7799-11e8-881d-f60a17f6523e.png)

**Comment by jco2** [comment]
I find them nice looking on paper actually. Getting rid of them would break the style and unity of the font since many letters have these serifs (the 'n' and the 'r' for instance).

**Comment by alerque** [comment]
I've printed thousands of resources and several whole books in this font and not noticed this as a problem. i rather like the character of the serifs actually. I suppose there isn't any harm in stylistic alternative glyphs with different serifs, but it certainly shouldn't be made the default or anything like that.

**Comment by khaledhosny** [comment]
I see no reason to change the serif if these two glyphs, but if someone is willing to do the work and provide a sensible pull request for stylistic alternates, I don’t mind merging it.
