### ISSUE TITLE
Can't embed Font in MS Publisher or MS Word

### ISSUE THREAD

**Issue by EgUG** [libertinus-fonts/libertinus#198]
I can't embed the fonts Libertinus Sans and Libertinus Keyboard in files of MS Word or Publisher. It works in MS PowerPoint. MS Word hast no error messages. MS Publisher tells me, that the font is a printer font and that it is not possible to embed the fonts (see image). Maybe the other fonts have the same problem. 
Can you fix it? 
Thank you.

![publisher_font_embedding](https://user-images.githubusercontent.com/41321085/42812661-abc6b546-89be-11e8-98e3-8ef4ed80531e.png)

**Comment by khaledhosny** [comment]
Does it happen with any other Libertinus fonts, or just these two? Having the error message in English might give me some clue what this is about (best is an actual error message in Word not a translation of it, so much gets lost in translation).

**Comment by EgUG** [comment]
I tested all fonts. It happens with any Libertinus font and I found a new problem with the semibold fonts. 

### The new Problem:
If Libertinus serif bold and serif semibold are installed, it is not possible to use semibold in MS Word, PowerPoint and Publisher. PowerPoint and Publisher do no not recognize them, Word makes no differences between bold and semibold (see picture).
![capture_001_18072018_104532](https://user-images.githubusercontent.com/41321085/42870849-34bea6aa-8a79-11e8-8a13-27dff869ec2c.jpg)

### The embedding problem: 
I have not a really error message. It just doesn't work. 
**Word 2016:**
By using "Embed fonts in the file" the font should be saved within the word document. Unfortunately Word and Powerpoint do not tell you if there are license restrictions. But nonrestricted fonts are easy by this way to embed.
![capture_002_18072018_105414](https://user-images.githubusercontent.com/41321085/42871041-b0260cfc-8a79-11e8-813d-ba46a17fea19.jpg)
But it doesn't work for this fonts. If you want to make a PDF-file with Word, the fonts wil not be embeded in PDF too.
**Publisher 2016:** 
It is the same problem. In Publisher you can "manage embeded fonts" and decide which font should be included in the file and you can see, if there are license restrictions.
![capture_003_18072018_110346](https://user-images.githubusercontent.com/41321085/42871314-577fef4a-8a7a-11e8-85ba-7470845e1441.jpg)
![capture_001_18072018_110626](https://user-images.githubusercontent.com/41321085/42871447-b4b3b520-8a7a-11e8-80ce-3cdc67fb14e3.jpg)
Unfortunately the font type is "printer", which ist not embedable. Ususally is the font type ist TrueType for emedable fonts.

**Comment by EgUG** [comment]
I tested [Source Serif Pro](https://github.com/adobe-fonts/source-serif-pro/releases/tag/2.000R). I can't embed it. It is the same notice, that the fontype ist 'printer'. I tested some more otf-files and some worked and some didn't. 
It seems to be that otf-files with postscript outlines are not embedable in MS Word and MS Publisher and otf-files with truetype outlines are embedable.

**Comment by khaledhosny** [comment]
Thanks for confirming. That is a software limitation and out of our hands. You can convert the font to TrueType yourself, though. See this Python script https://github.com/fonttools/fonttools/blob/master/Snippets/otf2ttf.py.
