### ISSUE TITLE
Needed extra pdfglyphtounicode config for ligatures (maybe)

### ISSUE THREAD

**Issue by Blaisorblade** [libertinus-fonts/libertinus#199]
Apologies for opening here a bug about `libertine` which might or might not apply.

The `acmart` class uses `libertine`, and one of its issues (https://github.com/borisveytsman/acmart/issues/167) shows problems with copy-pasting text, fixed by mapping glyphs to unicode sequences using `pdfglyphtounicode`.

@kberry and @ozross discuss relevant issues here (https://github.com/borisveytsman/acmart/issues/294#issuecomment-405108878) and suggest upstreaming them.

If libertinus uses different glyph names handled by `glyphtounicode`, changes will not be necessary.

Here are the directives we have in `acmart`:
```
\pdfglyphtounicode{t_t}{0074 0074}
\pdfglyphtounicode{f_t}{0066 0074}
\pdfglyphtounicode{T_h}{0054 0068}
```

**Comment by khaledhosny** [comment]
We don’t provide any TeX or LaTeX support file, so I don’t think we have anywhere to put these lines. You probably want to contact the maintainer(s) of LaTeX package(s).

**Comment by khaledhosny** [comment]
Furthermore, we did many changes that should improve text extraction from PDF files, so it might not be needed at all (at least for the OpenType fonts, Type 1 fonts are not maintained by us).

**Comment by Blaisorblade** [comment]
Sorry for wasting your time, you're completely right. Thanks for the kind answer!

**Comment by khaledhosny** [comment]
No problem.
