### ISSUE TITLE
BlueValues problem prevents printing LibertinusSerif-Semibold

### ISSUE THREAD

**Issue by jdietrch** [libertinus-fonts/libertinus#205]
I created a PDF that uses LibertinusSerif-Semibold. When I tried to process and print this file on a Fiery FS150 Pro it failed with this error:
```
PS invalidfont error, offending command "definefont" BlueValues
--nostringval--
```

So I ran fontlint on the otf, and it said this:
```
ERROR     65 Disordered elements in either the BlueValues or OtherBlues
             entries in the PostScript Private dictionary
```

Looking in the sfd, I saw that the values are indeed out of order:
```
BlueValues 47 [-12 1 433 447 474 460 563 580 645 662 690 698]
```

So I swapped the numbers `474` and `460`, regenerated the otf, and reexported the PDF with the fixed font. That PDF printed just fine.

So I think that the BlueValues line in `LibertinusSerif-Semibold.sfd` needs to be fixed.

I also ran fontlint on the other otf files, and it indicated a couple problems with BlueValues in `LibertinusKeyboard-Regular` as well:
```
ERROR     65 Disordered elements in either the BlueValues or OtherBlues
             entries in the PostScript Private dictionary
ERROR     67 Elements too close in either the BlueValues or OtherBlues
             entries in the PostScript Private dictionary (must be at least
             2*BlueFuzz+1 apart)
```

Thank you,
James

**Comment by khaledhosny** [comment]
It would be great if you can make a pull request.

>              entries in the PostScript Private dictionary
>
> Looking in the sfd, I saw that the values are indeed out of order:
>
> BlueValues 47 [-12 1 433 447 474 460 563 580 645 662 690 698]
>
> So I swapped the numbers 474 and 460, regenerated the otf, and reexported
> the PDF with the fixed font. That PDF printed just fine.
>
> So I think that the BlueValues line in LibertinusSerif-Semibold.sfd needs
> to be fixed.
>
> I also ran fontlint on the other otf files, and it indicated a tly, vie
> <https://github.com/libertinus-fonts/libertinus/issues/205>
>

**Comment by jdietrch** [comment]
Sure, I can do that. Before I do, though, could you comment on what should be done in the case of `LibertinusKeyboard-Regular`? Because I only just started learning about BlueValues today!

The original BlueValues line in `LibertinusKeyboard-Regular` is this:
```
BlueValues 47 [29 41 361 374 460 474 568 578 524 537 555 568]
```
Putting the values in order results in this:
```
BlueValues 47 [29 41 361 374 460 474 524 537 555 568 568 578]
```
But the font validation in FontForge still complains about that line because of the two `568`s. With the default BlueFuzz of `1` there needs to be a gap of at least 3 between the end of one pair (` 555 568`) and the start of the next (`568 578`). That would mean changing that line to something like this:
```
BlueValues 47 [29 41 361 374 460 474 524 537 555 566 569 578]
```

What do you think would be best to do?

**Comment by khaledhosny** [comment]
I’m not really sure, but I’d just merge the last two pairs:
```
BlueValues 39 [29 41 361 374 460 474 524 537 555 578]
```
