### ISSUE TITLE
Asterisk is high above baseline in Mono font; problematic for code listings

### ISSUE THREAD

**Issue by jfbu** [libertinus-fonts/libertinus#206]
MWE:

```
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Libertinus Serif}
\setsansfont[Scale=MatchLowercase]{Libertinus Sans}
\setmonofont[Scale=MatchLowercase]{Libertinus Mono}

%\setmonofont[Scale=MatchLowercase, FakeStretch = 0.8]{Libertinus Mono}
%\usepackage{libertinus-otf}% testing
\begin{document}

The asterisk * is at high position, this is ok.

\texttt{The asterisk * is at high position also in monospaced font,
  problematic for code listings. It is small, furthermore.}


\end{document}
% Local variables:
% TeX-engine: xetex
% End:
```

produces (TeXLive 2018, updated August 3.)

![capture d ecran 2018-08-02 a 11 52 33](https://user-images.githubusercontent.com/2589111/43576837-924acb32-964a-11e8-954b-d6208f0d709d.png)

Possibly relates #63, #164 

I am not familiar with OpenType fonts in general, is there some stylistic alternate here which already fixes that "issue"? I opened the font in FontForge but saw nothing particular on selecting the glyph about alternates.

**Comment by khaledhosny** [comment]
The monospace asterisk was the same size as the serif one, but you were scaling down the font which made it look smaller. However, I agree that monospace asterisk should be larger and lower, so I did just that.

**Comment by jfbu** [comment]
ah, allright, thanks for the explanation, and great to hear about this larger and lower asterisk looking forward to use it soon
