### ISSUE TITLE
Libertinus Keyboard lost many symbols

### ISSUE THREAD

**Issue by RGB-es** [libertinus-fonts/libertinus#208]
I've been using Libertinus Keyboard to indicate keyboard shortcuts in a manual I'm writing, but it seems that the latest development version lost many "keys," like enter, tab, shift, etc.

**Comment by khaledhosny** [comment]
What are the code points of the missing keys?

**Comment by RGB-es** [comment]
U+E16E for backspace
U+E171 for Alt
U+E172 for AltGr
U+E173 for Ctrl
U+E174 for Shift
U+E175 for tab
U+E176 for Enter
U+E178 to E183 for F1 to F12
U+E188 for Fn
U+E189 for Home
U+E18A for Del
U+E18B for Ins
U+E18C for space bar
U+E18E for End

There are more, but I don't use them.

**Comment by khaledhosny** [comment]
They can be accessed as ligatures (few were not accessible, but they are now):
```
Back
Alt
AltGr
Ctrl
Shift
Tab
Enter
F1
Fn
Home
Del
Ins
Space
End
```

**Comment by RGB-es** [comment]
Wow! That's neat! I'll need to rewrite many things, but I don't care, this is just too cool! Thanks!
