### ISSUE TITLE
T leg placement varies between weight

### ISSUE THREAD

**Issue by SirPL** [libertinus-fonts/libertinus#209]
Hi,
I have seen the 'T' issue #195 but I found one more thing: The leg of Regular and Bold capital T is not placed in the center. However that's not the case for Semibold.
Take a lok at the distance of some points of the Regular - the leg is moved a bit to the right:
![obraz](https://user-images.githubusercontent.com/11311649/43996115-237df7fa-9dbc-11e8-990a-27c98dc188fe.png)
We should either move the leg in Semibold to the right or center it in other weights.

**Comment by KrasnayaPloshchad** [comment]
One possible solution is to integrate OT font variation, then regenerate different font weights from static font instances, but this requiring FontForge add suppor for this.

**Comment by khaledhosny** [comment]
I don’t think there is a rule that mandate such consistency.
