### ISSUE TITLE
Small caps figures would be a nice addition

### ISSUE THREAD

**Issue by skef** [libertinus-fonts/libertinus#211]
Thank you for all your great work with Libertinus.
After experimenting with various combinations of OpenType options, it looks to me like figures to match lower case small caps glyphs are not currently supported. Here is an illustration from another font:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6175836/44573632-00513b00-a73c-11e8-9a09-3570f579fc47.jpg)

I am not a font expert by any means, but I think it would be reasonable to make these the lining figures (and therefore the default) when small caps is activated. The "case" variants are already a reasonable alternative for anyone needing larger lining figures, and there's always the additional option of turning off small caps.

**Comment by khaledhosny** [comment]
Feel free to send a pull request.
