### ISSUE TITLE
 libertinus type1 package

### ISSUE THREAD

**Issue by rdtennent** [libertinus-fonts/libertinus#213]
As far as I know, no package supports libertinus use with traditional engines.  Would it be acceptable if I revised the existing libertine package to be based on the libertinus otf fonts?  Or should I create a new libertinus-type1 package?  Or revise the libertinus package to add type1 support?

Bob T.

**Comment by khaledhosny** [comment]
We don’t maintain any LaTeX packages. I think you need to talk to the package maintainer(s).

**Comment by rdtennent** [comment]
CTAN states that *you* are the maintainer of the libertinus package.  And *I'm* the maintainer of the libertine package.  In any case, the question has to do with *using* the libertinus fonts.  Are you agreeable to my taking over maintenance of the libertinus package and adding type1 support.?  I'd prefer that this discussion were private but I'm unable to e-mail you because of your spam blocking.

**Comment by khaledhosny** [comment]
My memory is failing me then. I really appreciate if you can take over the Libertinus package, thanks.

**Comment by khaledhosny** [comment]
Do you mean [this package](https://www.ctan.org/pkg/libertinus)? I think I’m just uploading the OTF files so that they are available in TeX Live (since TUG funded some of the development of the math fonts), but there is no actual LaTeX package. I don’t again have any objections about handing it over to you, you will certainly do a much better job than I’m capable of.

**Comment by rdtennent** [comment]
OK thanks.  And I guess you have no preference among the three options I suggested?  I'll consult with Herbert Voss and Karl Berry about that.  Do you upload updates to CTAN when there are new releases?

**Comment by khaledhosny** [comment]
Yes, feel free to do what you think is the best.
