### ISSUE TITLE
Sans-BoldItalic has no features

### ISSUE THREAD

**Issue by rdtennent** [libertinus-fonts/libertinus#214]
% otfinfo -f libertinussans-bolditalic.otf

returns nothing;  Regular,  Bold and Italic are OK.  Serif-BoldItalic is OK.

**Comment by rdtennent** [comment]
I've just realized that that font is installed in TeXLive by libertinus-otf and is presumably not your responsibilty.

**Comment by alerque** [comment]
This is not a CTAN issue. Sans Bold Italic has never existed. It didn't exist back in the Linux Libertine days, and it hasn't to my knowledge ever existed in Libertinus. The Mono face also has no styles at all.

From the TeX side you can fake it using the `fontspec` packages auto fakes, but they aren't as good as the real thing.

```tex
\documentclass{article}
\usepackage{fontspec}
\begin{document}
\huge
\setmainfont{Libertinus Serif}
\setsansfont[BoldItalicFeatures={FakeBold=3}]{Libertinus Sans}
\setmonofont[AutoFakeSlant=0.2,AutoFakeBold=3]{Libertinus Mono}
\noindent
Libertinus Serif\\
\textbf{Libertinus Serif Bold}\\
\textit{Libertinus Serif Italic}\\
\textbf{\textit{Libertinus Serif Bold Italic}}

\noindent
\textsf{%
Libertinus Sans Regular\\
\textbf{Libertinus Sans Bold}\\
\textit{Libertinus Sans Italic}\\
\textbf{\textit{Libertinus Sans Fakebold Italic}}
}

\noindent
\texttt{%
Libertinus Mono\\
\textbf{Libertinus Mono Fakebold}\\
\textit{Libertinus Mono Fakeslant}\\
\textit{\textbf{Libertinus Mono Fakebold Fakeslant}}
}
\end{document}
```

**Comment by hvoss49** [comment]
Or simply use

\usepackage{Libertinus-otf}

Herbert

**Comment by alerque** [comment]
True, thanks for pointing that out @hvoss49. Although that doesn't go quite as far as the manual example I just posted because it doesn't cover the mono font variants. Perhaps we could get AutoFake(Bold|Slant) setup for that in the package as well? The existence of LaTeX packages for handling this is probably something I should document here in the font project as well, eh?

**Comment by alerque** [comment]
I take that back. It was my testing that was flawed, I checked the code and Mono is supported. So yes, that's by far the best way to go.

There is also a meta package that hunts for the right backend setup depending on TeX engine:

```tex
\usepackage{libertinus}
```
