### ISSUE TITLE
Center ogonek in Native American languages

### ISSUE THREAD

**Issue by brawer** [libertinus-fonts/libertinus#216]
For Native American languages, it would be nice to add variants where the ogonek is centered in ĄąĘęǪǫŲų. The current form is appropriate for European languages, but one could add centered variants for OpenType language systems `NAV`, `ATH`, etc.

See [Typographical notes for Ogonek in the English Wikipedia](https://en.wikipedia.org/wiki/Ogonek#Typographical_notes).

**Comment by KrasnayaPloshchad** [comment]
Another possible solution is making use of CGJ to produce alternative behavior.

**Comment by KrasnayaPloshchad** [comment]
Additional solution is making use of CGJ, that is: A, CGJ, Ogonek; in case of this sequence you can also make Ogonek centered, and independent of specific language systems.

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
