### ISSUE TITLE
Initials font is very incomplete

### ISSUE THREAD

**Issue by khaledhosny** [libertinus-fonts/libertinus#22]
Some people and complaining about this, I don’t know for sure what this font was for so logging this here for reference.

**Comment by RGB-es** [comment]
I think the Initials font was intended for creating Drop Caps, like on this example 

![libertinusinitials](https://cloud.githubusercontent.com/assets/7756783/12872744/32b06188-cdab-11e5-96e8-8fe6a1f3f0e8.png)

[a few fonts I know (for example, some of the  [Bhikkhu Pesala fonts](http://www.softerviews.org/Fonts.html)) have this as the "Contextual → Initial forms" (+init) OpenType feature, but a separated font file could be useful for people using Writer or other non OpenType aware software]

Regards,
Ricard

**Comment by Crissov** [comment]
The incompleteness may be the reason why it’s showing Hebrew letters in OS X’s font collection tool.

![Libertinus Serif Initials showing Hebrew characters in OS X](https://cloud.githubusercontent.com/assets/6200185/17418297/15bb11a2-5a98-11e6-9ac0-bc30f3229c36.png)

**Comment by alerque** [comment]
I've used this in a couple past projects for initial drop-caps. If it were to be developed further I would prefer to see it as an Open-Type feature.

**Comment by Crissov** [comment]
There’s no special OT feature for drop capitals (like *`drop`), so would you prefer `titl`, `ss##`, `init`, `isol` or something else? What do other fonts use?

**Comment by khaledhosny** [comment]
`init` and `isol` are inappropriate (they are for Arabic-like joining) and `titl` is not appropriate either. I’d go for a stylistic set.

**Comment by Crissov** [comment]
Yes, I thought so, although `ss##` should always be the last resort in my opinion, because it requires extra documentation and author action or higher-level code, e.g. [`@font-feature-values` in CSS](http://www.w3.org/TR/css-fonts-3/#font-feature-values).

**Comment by khaledhosny** [comment]
Not doing anything here. Anyone using this font is free to contribute enhancements.
