### ISSUE TITLE
Hanging Punctuation should be enabled

### ISSUE THREAD

**Issue by EvanEdwards** [libertinus-fonts/libertinus#220]
Pardon my technical ignorance here, but I believe -- in having used the feature with Linux Libertine G in LibreOffice via "Linux Libertine G:hang=1" -- that hanging punctuation is a OpenType feature that must be built into the font file.

I feel it would be quite a nice feature to have for a variety of use cases, especially for book, magazine, and news column layouts where justified text is typically used and hanging punctuation makes a for significantly more natural right edge.  Support is becoming far more common in software.

I have no idea if this is a relatively easy addition (possibly using metrics cribbed from LLG?), or if it is something that would need to be "hand kerned" for each bit of punctuation.

(And a big thank you to everybody who works on this project!)

**Comment by khaledhosny** [comment]
Linux Libertine G is a Graphite not OpenType fonts, so not everything it supports is readily available in OpenType. Though there is feature for [Optical Bounds](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#a-nameopbd-idopbdatag-opbd) (more general than just hanging punctuation), there is virtually no application that supports it (the features needs to be selectively activated at line bounds), so there is no much point in adding it.

**Comment by RGB-es** [comment]
@EvanEdwards You may be interested in exploring the use of Libertinus fonts with XeTeX or LuaTeX with the microtype package https://ctan.org/pkg/microtype

**Comment by EvanEdwards** [comment]
@RGB-es - Thanks.  I'm actually coming _from_ ConTeXt, which is part of why I'm looking for this in LibreOffice, which I need to use for some upcoming projects.  As @khaledhosny says, it appears that it's poorly supported as of yet, especially compared to the similar feature in Graphite.

Bummer.

**Comment by cmahte** [comment]
If I REALLY wanted hanging punctuation, and the punctuation in question is known to properly separate start and end.  (That is, quotes are directional, and a single quote is not also an apostrophe.) 

If I know where the punctuation is, why can't I just use alternate glyphs that 'hang out', and then kern them when they aren't on the end of a row?  That is an alt glyph table for opening punctuation that draws them 'before' the zero point. closing glyphs are drawn 'after the close'. and kerning to each other for events like ." and to the space characters keep them normal appearing when they aren't on the end of a line?  What doesn't work with this solution?  is there some rule in the font design that disallows that much beyond the edge of the glyph space?  There is a jalt table, and if I'm reading opentype correctly an rtbd and lfbd for kerning. however the rtbd and lfbd are for kerning at the edge, not everywhere else. So it is possible opentype doesn't have a table that covers what I'm thinking would be the simplest font solution. 

Is this already tried and failed?
