### ISSUE TITLE
Status of design guidelines file

### ISSUE THREAD

**Issue by nsemrau** [libertinus-fonts/libertinus#221]
I was looking for opportunities to contribute further to the documentation and `/documentation/Design-Guidelines.md` caught my attention.

The file looks out of date (even still only talks about Libertine fonts) and has a few typos. I was wondering if the file's status is like `/README.linuxlibertine.txt` in the sense that it is "frozen" and for documenting the project's legacy before the fork or if you are welcoming fixes/enhancements to the guidelines?

If the file is still considered active, I plan to iron out the typos and to look for opportunities to update some out-of-date statements made about a decade ago.

**Comment by khaledhosny** [comment]
The design document originates from Linux Libertine indeed, but, unlike `README.linuxlibertine.txt`, I’m all open to updating and maintaining it.
