### ISSUE TITLE
"Th" Ligature

### ISSUE THREAD

**Issue by ToddOhl** [libertinus-fonts/libertinus#230]
This seems to have been moved to a "Rare" ligature in between v6.4 and v6.6.

Why? This could cause a lot of template maintenance just to adjust a ligature setting.

**Comment by RGB-es** [comment]
The Th ligature is discussed here:
https://github.com/libertinus-fonts/libertinus/issues/104

**Comment by khaledhosny** [comment]
See #104. You don’t need to do anything unless you really want that ligature, and my perceptions is that most people either do not want it or are indifferent.
