### ISSUE TITLE
Fill in space/hyphen/joiner/separator glyphs? Add leading text 'justification' kerning?

### ISSUE THREAD

**Issue by cmahte** [libertinus-fonts/libertinus#232]
Can you add these missing whitespace and space-like non-whitespace glyphs?

Uni | Description | Note
----|-------------|----
0008| Backspace |(same as ZWSP)
034F| Combining Joiner |(same as ZWSP)
00AD| Soft hyphen |(same as a ZWSP)
2043| Hyphen bullet |(mid height dash about the same as a narrow space) 
205F| Medium Math Space
2060| Word joiner |
2063| Invisible separator |
2028| Line separator |
2029| Paragraph separator |
3000| Ideographic Space |(space that spans the same in X as the vertical leading, likely a little larger than em space.)
FEFF| Zero width no-break space |
FFF9 |INTERLINEAR ANNOTATION ANCHOR|
FFFA |INTERLINEAR ANNOTATION SEPARATOR|
FFFB |INTERLINEAR ANNOTATION TERMINATOR|

In all cases, these glyphs provide special functions as described in the Unicode standard in apps if they are present in the font, and supported in the app. For example, the various hyphen characters are detected and possibly show up as alternatives in a layout engine. 

These represent 
Items in section various glyphs described in 11, 16.1 and 16.3 in this [document](http://unicode.org/L2/L2010/10038-fcd10646-main.pdf).

I'm working through what it takes to make LibreOffice produce real typeset text. 
And one of the big gaps between LO and Indesign is the lack of proper justified text mode with allowances for punctuation. 

So, I'm studying implementing some negative tracking/kerning on punctuation. By this, I originally meant including a NWJ character in front of leading quotes and automatically detecting them in a script and kerning them back.  This won't work at the end of text rows, but it will work for leading text. 

Except that's exactly what the font does in the kern table. In order to 'track or kern before the starting margin, the kern needs to be on a non whitespace character. Which brings me to the list above, and  that there are other whitespace functions that the font isn't aware of but apps have enabled, but deal poorly with missing glyphs.

**Comment by khaledhosny** [comment]
* U+0008 is a control character, it does not need a glyph in the font to work (and these ASCII control characters are of no use now AFAIK).
* U+034F COMBINING GRAPHEME JOINER is an invisible control character, so a system needing a glyph for it is probably broken and won’t correctly handle it anyway. But I don’t mind adding an empty zero width glyph for it. The same applies for U+00AD,  U+2060, U+2063, U+2028 and U+2029.
* No idea what U+FFF9, U+FFFA and U+FFFB, but again they seem to be control characters.
* U+3000 Ideographic Space is for CJK fonts, so out of scope. 
* U+FEFF Zero Width no-break space is deprecated as a zero-width space, it is now used as BOM mark.
* U+2043 and U+205F look useful.

I don’t mind if you want to send a PR to add glyph for all these characters, but I find having glyphs for them is rather pointless.

**Comment by cysouw** [comment]
The invisible control characters are important for various use cases, most prominently for determining line breaks and automatic hyphenation. For example, I use a notation (meaning unimportant here) that looks like [NA|–N] which should not be broken up at the end of a line. However, most typesetters (e.g. Webbrowsers) will allow words to be broken up at hyphens and/or pipes. To prevent breaking at those points, you can add for example U+2060 at places where no break should occur.

I personally use this, and it seems like a minor effort to add such a code point to the font. Please reconsider this issue.
