### ISSUE TITLE
Add support for CGJ

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#235]
With CGJ character you can also create altenate forms with combining diacritics while necessary, and not be subject to canonical reordering. In Libertinus font this can be done in two steps:
* Add a zero width glyph at that codepoint
* Add mark attachmants with CGJ

**Comment by khaledhosny** [comment]
None of this is needed for CGJ to work. Please open specific issues about actual bugs you face, thanks.
