### ISSUE TITLE
Illformed U+1D6DB

### ISSUE THREAD

**Issue by Bolpat** [libertinus-fonts/libertinus#238]
In Libertinus Math, MATHEMATICAL BOLD PARTIAL DIFFERENTIAL (U+1D6DB) is not bold.

**Comment by khaledhosny** [comment]
This was fixed in commit cfad2f744e13e68677fb19c3c23e5500ae08ae5d back in Jun while fixing https://github.com/libertinus-fonts/libertinus/issues/193. Please restest with files from the repo.
