### ISSUE TITLE
\langle and \rangle automatic sizing (bad behaviour)

### ISSUE THREAD

**Issue by kauesena** [libertinus-fonts/libertinus#242]
The vertical bar is not properly sized when used with angled brackets. I have tested the same code with other fonts and the discrepancy does not appear. The following picture is the result obtained by this line: `\[\left|a\right\rangle |a\rangle \left|\sum a\right\rangle\]`
![screenshot from 2018-11-02 19-13-26](https://user-images.githubusercontent.com/30255100/47943216-c175f900-ded3-11e8-94b9-166520f14991.png)
The only math packages used were `mathtools` and `unicode-math`.

**Comment by khaledhosny** [comment]
Fixed in #257.
