### ISSUE TITLE
Bug with combining ogonek and accute for lower case vowels in Native American Languages

### ISSUE THREAD

**Issue by ryankasak** [libertinus-fonts/libertinus#243]
Many Native American languages mark nasal vowels with an ogonek and also use an acute accent on that same vowel. For Libertinus, using both a combining ogonek and acute on a lower case i causes both the tittle and the acute to appear at the same time.

![](https://i.imgur.com/FUXsZcO.png)

In LaTeX, when compiled in XeLaTeX or LuaLaTeX,unaccented vowels with ogoneks are fine when plain, italic, or bold, but in small caps, the i, o, and u do not become small caps. When both the combining ogonek and acute accent are present, the acute is centered only for plain a and e, and off-center everywhere else.

Furthermore, when an acute accent is placed on the i with ogonek (į́), both the acute and the tittle appear at the same time, when only the acute should appear on the i with combining ogonek.

Is there a workaround for this?

**Comment by khaledhosny** [comment]
ı̨́ would have been a work around (dotless i with combing acute and ogonek), but the ogonek is badly positioned, so it does not work either.

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
