### ISSUE TITLE
Add previews in the README

### ISSUE THREAD

**Issue by sprt** [libertinus-fonts/libertinus#244]
To me, the most important thing about a font is the way it looks. I think you guys should definitely add image previews in the README for potential users!

**Comment by khaledhosny** [comment]
Can you send a pull request?

**Comment by FloraCanou** [comment]
I'd like to comment on the current preview image. 

It sucks in spacing: in regular and bold type the italic is wider than the roman while in semibold the opposite. Besides, the Th ligature is still there in the Display? Maybe I'm nitpicking, but I would try to hide those inconsistencies if I were to host the project. 

As an introducing image I don't expect it to show every type. A text in regular roman would work well. Less is more.
