### ISSUE TITLE
Anchoring of top tie bar, used in affricates

### ISSUE THREAD

**Issue by kopeckyf** [libertinus-fonts/libertinus#245]
This is a bug inherited from Libertine. The upper row is showing Unicode output (p͡f, etc.). The lower row shows output from the TeX package `tipa`. In cases where Unicode has to be used, there is no known way to produce affricates correctly.

![tipavsunicode](https://user-images.githubusercontent.com/10461729/48914482-e24ec000-ee7b-11e8-9483-6139940cbe51.png)

**Comment by khaledhosny** [comment]
I have no clue how to fix this, I don’t think we can have a mark positioned over two glyphs in OpenType. The only workaround I can think of right now is making the tie glyph higher than the capital height, but this will make ts one look less ideal and still clash over accented characters (probably not an issue in practice).

**Comment by kopeckyf** [comment]
Thank you! Regarding your 1st question, all Latin uppercase, ʃ ("Esh"), ʔ (Glottal stop) and all Greek upper- and lowercase letters are in this set. The most important Greek letter is probably θ (theta).

Are you planning to include the code you posted in the major Libertinus release?

**Comment by khaledhosny** [comment]
I checked a few fonts, and they all seem to just put the tie higher than the glyph ascender which I think is good enough and there is no need to overwork it.
