### ISSUE TITLE
U+0302 Combining Low Line should be contiguous 

### ISSUE THREAD

**Issue by brawer** [libertinus-fonts/libertinus#248]
According to [Wikipedia](https://en.wikipedia.org/wiki/Macron_below), which unfortunately does not cite a source for its claim, `U+0302 COMBINING LOW LINE` should lead to a continuous underline. Current Libertinus fonts sometimes give a broken line. Here’s `a̲i̲ e̲a̲ i̲i̲ i̲e̲ e̲i̲` in current Libertinus Sans/Serif-Bold when shaped by HarfBuzz; expected a continuous underline for each letter pair. See also https://github.com/google/roboto/issues/98 for the same bug in the Roboto font.

![image](https://user-images.githubusercontent.com/1527880/49881124-db3d2100-fe2d-11e8-84cd-13cf7c295fef.png)
![image](https://user-images.githubusercontent.com/1527880/49881114-d0828c00-fe2d-11e8-9d42-44ebb288edae.png)

**Comment by khaledhosny** [comment]
This is tricky to implement in a variable width font as it would require multiple underline glyphs and contextual substitution. I happen to have wrote a [FontForge Python code](https://github.com/alif-type/amiri/blob/92979a1fa79fe663b2de006a9f96ae9904785ebe/tools/build.py#L156-L232) to automates this for Amiri (handles both overline and underline characters), if anyone is interested in porting it to Libertinus.

**Comment by brawer** [comment]
I’ve found the specification for this. The Unicode Standard v11.0.0 writes in section 6.2 “General Punctuation” on page 273:

> _**Spacing Overscores and Underscores.**_ U+203E OVERLINE is the above-the-line counterpart
to U+005F low line. It is a spacing character, not to be confused with U+0305 COMBINING
OVERLINE. As with all overscores and underscores, a sequence of these characters
should connect in an unbroken line. The overscoring characters also must be distinguished
from U+0304 COMBINING MACRON, which does not connect horizontally in this way.
