### ISSUE TITLE
Request: Banana brackets: ⦇ ⦈

### ISSUE THREAD

**Issue by timtro** [libertinus-fonts/libertinus#253]
I can see, Khaled, that you're quite busy with bugs and other more pressing issues. If you ever get a chance, there are areas of computer science where these brackets are quite useful. Most people (using LaTeX and friends) force a collision between a lr/vert and a lr/paren to fake it.

**Comment by nsemrau** [comment]
Codepoints:
⦇ = U+2987: Z NOTATION LEFT IMAGE BRACKET
⦈ = U+2988: Z NOTATION RIGHT IMAGE BRACKET

**Comment by timtro** [comment]
> Codepoints:
> ⦇ = U+2987: Z NOTATION LEFT IMAGE BRACKET
> ⦈ = U+2988: Z NOTATION RIGHT IMAGE BRACKET

I'm sorry I didn't think to include this in the original request. Thanks.
