### ISSUE TITLE
Lack of space before big delimiters

### ISSUE THREAD

**Issue by hanche** [libertinus-fonts/libertinus#254]
I don't know if this is an issue with lua(la)tex or the libertinus font:

    \documentclass[a5paper]{article}
    \usepackage{luatex85,fontspec,unicode-math}
    \setmainfont{Libertinus Serif}
    \setmathfont{Libertinus Math}
    \begin{document}
    $f(x)=f\bigl(x(t)\bigr)$ –
    $\lvert\int_a^bf(t)\,dt\rvert$ –
    $\Bigl\lvert\int_a^bf(t)\,dt\Bigr\rvert$
    \end{document}

This produces the output in the attachment. As you can see, the space before ordinary delimiters is normal, but there is essentially no space before big delimiters.

![screenshot 2019-01-10 at 18 08 33](https://user-images.githubusercontent.com/518961/50988703-b233ad00-150d-11e9-9db1-eaa90b964959.png)

**Comment by hanche** [comment]
Since we made some progress in tex.se chat ([starting here](https://chat.stackexchange.com/transcript/message/48446566#48446566)), I thought I could add a brief summary here, for ease of reference:

The problem is that luatex does not insert a math italic correction at the boundary between math and non-math. And since the `\bigl(` construct and friends create an `\hbox`, such a boundary results. A workaround is to insert a non-breaking zero width space, `\U200B`, in front of each big delimiter.

Possibly, a better solution would be to create math cut-in data for the font, but that is likely going to be a large amount of work.

**Comment by khaledhosny** [comment]
Closing for now, nothing actionable here for us.
