### ISSUE TITLE
Top tie bar does not display in Semibold-Italic

### ISSUE THREAD

**Issue by kopeckyf** [libertinus-fonts/libertinus#259]
The top tie bar, used in affricates, now works very well in Libertinus-Italics and Libertinus-Semibold. Thank you for the work on this previous issue, it is highly appreciated. 

However, in Libertinus-SemiboldItalic, the top tie bar does not display at all. As far as I see, this is a bug inherited from Libertine.

Here is an illustration of the issue. The characters are inserted in Unicode, the typesetting engine is XeLaTeX.
![screenshot_20190213_105927](https://user-images.githubusercontent.com/10461729/52703441-a446d100-2f7e-11e9-878a-8f042be6cfb4.png)

**Comment by skef** [comment]
That range of glyphs appears to be kind of scrambed. Part of the problem traces to 9da4392d66dd81564b482f73c38dfbcb47aa52d7 . Before that the appear to have had accurate names but inaccurate Unicode encodings. That update made the names match the encoding but not (of course) the glyph. Still, the old names may provide the easiest route to the correct mapping.

**Comment by khaledhosny** [comment]
I fixed the wrong Unicode values. Feel free to contribute the missing tie glyph.
