### ISSUE TITLE
Add U+AB52 and U+A793 (see the SDF attachment)

### ISSUE THREAD

**Issue by grafikmuzik** [libertinus-fonts/libertinus#260]
Hi,

In January 2015, Philipp Henning Poll, aka Gillian, helped me to add two glyphs to the LinuxLibertine font (see the SDF file, in the ZIP attachment, at U+AB52 and U+A793):

- LATIN SMALL LETTER U WITH LEFT HOOK (U+AB52)
- LATIN SMALL LETTER C WITH BAR (U+A793)

Philipp was supposed to integrate these glyphs into LinuxLibertine, but he suddenly stopped responding (I hope he's alive).

Could you add these glyphs to Libertinus? 

These two characters are useful for French dialectologists who need to use the "Rousselot-Gilliéron alphabet".

Thanks!
Signed grafik.muzik

[aB52-a793-LinLibertine_R.zip](https://github.com/libertinus-fonts/libertinus/files/2906453/aB52-a793-LinLibertine_R.zip)

**Comment by skef** [comment]
U+A792 (#196) being right next door.

**Comment by grafikmuzik** [comment]
I see this issue was close 45 minutes ago. What does it mean? Will my request be considered?

**Comment by khaledhosny** [comment]
The glyphs were merged into Libertinus Serif Regular font.

**Comment by grafikmuzik** [comment]
Nice! Thanks a lot for this merge and for your quick answer :)
