### ISSUE TITLE
Make superscript and subscripts kerned with ZWJ

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#261]
With this feature you will make superscript and subscript characters sightly joining into one block, while a zero width joiner inserted between them.

![Example](https://i.imgur.com/hyQ2VWI.png)
For example, while you insert a zero width joiner between ₆ and ⁴, ₆ will shifted to the right, ⁴ will shifted to the left, so they will placed in one piece.
To implement this feature, you can add the kernings (or other features) with zero width joiner, then, althrough you want to drop this feature from superscript and subscript characters, this feature will still be available and optional to users whose still want to use that (for example, me), and it would break out the technical limits within other software environments which prevent such presentation.

**Comment by khaledhosny** [comment]
Unicode super and subscripts are not encoded for typographic superscripts and are inadequate for math or chemical typesetting.

**Comment by KrasnayaPloshchad** [comment]
That’s sad.
