### ISSUE TITLE
frac/sups/sinf lookup order change 

### ISSUE THREAD

**Issue by skef** [libertinus-fonts/libertinus#262]
The other changes you made after my commit are more or less matters of taste. (I really would have preferred keeping the figure tables separate.) Regardless, c5171b2ddce324a55d8cc869b0f5e9c91f7dc8c8 
is a substantial and, I think, incorrect change. Frac is supposed to (or intended to) have precedence over sinf and sups, as suggested by the ordering in `gsub.fea`. By moving the "directly" included sinf/sups tables before frac, you've given those features higher precedence.  The two tables were there for a substantial ordering reason.

**Comment by khaledhosny** [comment]
All these features (`frac`, `sups`, `subs`, `sinf`) are off by default features that should not be enabled globally; they have to be enabled for selected ranges of text. So I don’t think why the order matter as enabling, say, both `frac` and `sinf` on the same range of text is rather meaningless. That being said, if you have an example that is broken by this change then I can try to figure out a fix.

The dedublication was mostly because it felt cleaner (but this is subjective) and to decrease file size (but apparently FontTools is smart enough to share the data even when lookups are duplicated), so I’m open to reverting it if there is a good reason.

**Comment by khaledhosny** [comment]
(I really hated the `#ifdef` jungle, so a different way to have `superiors.fea` and `inferriors.fea` files and `include()` them inside the respective lookups)

**Comment by skef** [comment]
1. The reason to keep it the same is because it was that way in Linux Libertine (Regular) and previous versions of Libertinus. If I produced examples they would likely be corner cases or look like bad practice, but the world has corner cases and people institute bad practices. The focus should be on ease of adoption. 

2. Driving substantive changes from "prettiness" concerns is not good engineering practice. And this doesn't look like a *decision* in the first place, given that it's very counter-intuitive to have the `gsub.fea` order not match the application order, and the `gsub.fea` order wasn't changed. 

3. I would like to think all this can serve as a flexible model for complex `.sfd`-based projects that want to use feature files. From that perspective having this problem is a good thing, because it means that whatever duplication-avoiding solution is arrived at serves as an illustration. It sounds like you would prefer "guts-only" `superiors.fea` and `inferiors.fea` files, and to just include those in each context. That's fine with me. 

4. Maybe, all else aside, if the person who did a bunch of the work wants *one* or even *two* things to wind up roughly a certain way, those don't cause obvious problems, and he or she is flexible on the particulars, it wouldn't be a big deal?

**Comment by khaledhosny** [comment]
It is not about prettiness, but convoluted code is harder to understand and maintain. The order of lookups looked insignificant, so I went with the simpler approach. Also, although I like to maintain backward compatibility, I only do so when it is sensible; I have changed things in backward-incompatible way in the past and will continue to do so in the future if I have too.

**Comment by skef** [comment]
Alright, well, if That's The Way It Is, you should leave the tables in small.fea, eliminate the include in `frac.fea`, and change the order in `gsub.fea` so that the feature file order matches the precedence.

**Comment by khaledhosny** [comment]
I tried the `#include` trick, and the `GSUB` table size is increased only by 4 bytes, so that is good enough for me.

**Comment by skef** [comment]
Thank you! Sorry about the attitude -- I have my moments.
