### ISSUE TITLE
Request: Another methods for slashed zero 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#264]
Unicode 12.0 introduced a new methods to produce slashed zero: 0 (U+0030) + VS1 (U+FE00). Since required glyph is already existed, you’re easy add a new feature to produce this variant if 0 is combined with VS1.
See: 
https://www.unicode.org/charts/PDF/U0000.pdf
https://www.unicode.org/Public/emoji/latest/emoji-variation-sequences.txt

**Comment by alerque** [comment]
Why do I get the feeling Unicode is starting to take Perl as its role model — Perl and it's 5749 perfectly valid ways to write a line of code that does exactly the same thing in the end.

**Comment by khaledhosny** [comment]
The variation sequence was actually introduced in Unicode 9.0 not new in 12.0, still no idea what it would be useful for.

**Comment by khaledhosny** [comment]
Hmm, this is the proposal that lead to this http://www.unicode.org/L2/L2015/15268-slashed-zero.pdf, seems to be math-oriented, and if we add this we should probably support 2205 FE00 as well.

**Comment by khaledhosny** [comment]
Anyone is free to contribute this.
