### ISSUE TITLE
Request: Mathematical Operators with VS1

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#265]
The Mathematical Operators block has sixteen variation sequences defined for standardized variants, use U+FE00 (VS01) to denote variant symbols. These variants should be working for:
U+2205 EMPTY SET
U+2229 INTERSECTION
U+222A UNION
U+2268 LESS-THAN BUT NOT EQUAL TO
U+2269 GREATER-THAN BUT NOT EQUAL TO
U+2272 LESS-THAN OR EQUIVALENT TO
U+2273 GREATER-THAN OR EQUIVALENT TO
U+228A SUBSET OF WITH NOT EQUAL TO
U+228B SUPERSET OF WITH NOT EQUAL TO
U+2293 SQUARE CAP
U+2294 SQUARE CUP
U+2295 CIRCLED PLUS
U+2297 CIRCLED TIMES
U+229C CIRCLED EQUALS
U+22DA LESS-THAN EQUAL TO OR GREATER-THAN
U+22DB GREATER-THAN EQUAL TO OR LESS-THAN

**Comment by khaledhosny** [comment]
Feel free to send pull requests.
