### ISSUE TITLE
Zip file capitalization

### ISSUE THREAD

**Issue by alerque** [libertinus-fonts/libertinus#266]
I'm trying to update distro packages for the 6.7 release, and the capitalization has changed on both the file itself and the extracted directory. This makes updates complicated because it isn't just a matter of bumping a release number.

Was this change on purpose? Is this the new norm?

**Comment by khaledhosny** [comment]
Yes and yes.

**Comment by alerque** [comment]
Well then, packagers beware!

([Arch Linux](https://aur.archlinux.org/packages/otf-libertinus) is updated.)
