### ISSUE TITLE
Semibold italic Cyrillics are terrible (bold italics are OK but Serbian lacks some letters)

### ISSUE THREAD

**Issue by kiwi0fruit** [libertinus-fonts/libertinus#271]
## bold italic (OK but Serbian lacks some letters):
![bold](https://user-images.githubusercontent.com/19735117/55541316-f985a000-56ee-11e9-9728-3c6340784b02.png)

## semibold italic (Terrible Cyrillic):
![semibold](https://user-images.githubusercontent.com/19735117/55541317-f985a000-56ee-11e9-9f6b-42160dced9c0.png)

Sample text:

(EN) The quick brown fox jumps over the lazy dog. (NL) Op brute wijze ving de schooljuf de quasi-kalme lynx. (CS) Nechť již hříšné saxofony ďáblů rozezvučí síň úděsnými tóny waltzu, tanga a quickstepu. (HU) Jó foxim és don Quijote húszwattos lámpánál ülve egy pár bűvös cipőt készít. (RO) Înjurând pițigăiat, zoofobul comandă vexat whisky și tequila. (RU) Разъяренный чтец эгоистично бьёт пятью жердями шустрого фехтовальщика. (BG) Огньове изгаряха с блуждаещи пламъци любовта човешка на Орфей. (SR) Фијуче ветар у шибљу, леди пасаже и куће иза њих и гунђа у оџацима. (EL) Ταχίστη αλώπηξ βαφής ψημένη γη, δρασκελίζει υπέρ νωθρού κυνός. Type your own text to test the font!

**Comment by kiwi0fruit** [comment]
@StefanPeev I'm simply informing you about this issue with Libertinus Serif semibold italic cyrillics.

**Comment by khaledhosny** [comment]
“Terrible” is not a bug report. Feel free to open specific issues with clear description, and/or contribute fixes.

**Comment by kiwi0fruit** [comment]
@khaledhosny *Facepalm* Are you blind?

**Comment by khaledhosny** [comment]
Just to let others know, I blocked him and reported the abuse.

**Comment by alerque** [comment]
@kiwi0fruit I don't know if you noticed the message in the readme about the project maintainer not currently doing new development on this project and currently only accepting bug reports or contributions, but asking for a redesign on an entire face is not something that falls under the umbrella of a bug report.

I agree the face is sub-optimal, but bold-italic is already low priority, semibold is somewhat behind the rest of the family, and both together I'm sure takes very low priority. On the other hand if somebody wanted to submit an overhaul to the semibold series to bring it up to par I'm sure it would be considered.

**Comment by davelab6** [comment]
Well done Khaled, you did the right thing
