### ISSUE TITLE
Serifs of IPA/African characters in Libertinus Sans (SF#297)

### ISSUE THREAD

**Issue by Crissov** [libertinus-fonts/libertinus#42]
I have just verified that [bug #297 filed against Linux Biolinum at Sourceforge](https://sourceforge.net/p/linuxlibertine/bugs/297/) also applies to Libertinus Sans (Regular and Italic), except for `Khook` (also see [SF#290](https://sourceforge.net/p/linuxlibertine/bugs/290/)). The listed glyphs show serifs although this font is s upposed to be sans-serif. I didn’t check PUA and hebrew characters.

| Unicode |  | Common name |
| --- | --- | --- |
| U+0181 | Ɓ | Bhook |
| U+0182 | Ƃ | Btopbar |
| U+0183 | ƃ | btopbar |
| U+0184 | Ƅ | Tonesix |
| U+018A | Ɗ | Dhook |
| U+018B | Ƌ | Dtopbar |
| U+018C | ƌ | dtopbar |
| U+0191 | Ƒ | Fhook |
| U+0194 | Ɣ | Gammaafrican |
| U+0195 | ƕ | hv |
| U+0196 | Ɩ | Iotaafrican |
| ~~U+0198~~ | Ƙ | ~~Khook~~ |
| U+0199 | ƙ | khook |
| U+019C | Ɯ | Mturned |
| U+019D | Ɲ | Nhookleft |
| U+019E | ƞ | nlegrightlong |
| U+01A2 | Ƣ | Oi |
| U+01A3 | ƣ | oi |
| U+01A4 | Ƥ | Phook |
| U+01A5 | ƥ | phook |
| U+01A6 | Ʀ | yr |
| U+01AC | Ƭ | Thook |
| U+01AE | Ʈ | Tretroflexhook |
| U+01B2 | Ʋ | Vhook |
| U+01B3 | Ƴ | Yhook |
| U+01B4 | ƴ | yhook |
| U+01B8 | Ƹ | Ezhreversed |
| U+01B9 | ƹ | ezhreversed |
| U+01BA | ƺ | ezhtail |
| U+01BE | ƾ | glottalinvertedstroke |
| U+01BF | ƿ | wynn |
| U+01F6 | Ƕ | Hv |
| U+01F7 | Ƿ | Wynn |
| U+021C | Ȝ | *Yogh |
| U+021D | ȝ | *yogh |
| U+0220 | Ƞ | *Nlegrightlong |
| U+0221 | ȡ | *dcurl |
| U+0224 | Ȥ | *Zhook |
| U+0225 | ȥ | *zhook |
| U+0234 | ȴ | *lcurl |
| U+0235 | ȵ | *ncurl |
| U+0236 | ȶ | *tcurl |
| U+0238 | ȸ | *db |
| U+0239 | ȹ | *qp |
| U+0241 | Ɂ | *Glottalstop |
| U+027E | ɾ | rfishhook |
| U+027F | ɿ | rfishhookreversed |
| U+1EFA | Ỻ | *Ll |
| U+1EFE | Ỿ | *Yloop |
| U+1EFF | ỿ | *yloop |
| U+20A2 | ₢ | cruzeiro |
| U+20A3 | ₣ | franc |
| U+20A7 | ₧ | peseta |
| U+20A8 | ₨ | *rupee |
| U+20AF | ₯ | *drachma |
| U+2106 | ℆ | *cadauna |
| U+210E | ℎ | *planck |
| U+210F | ℏ | *hbar |
| U+2116 | № | numero = afii61352 |
| U+2119 | ℙ | *Pdoublestruck |
| U+211D | ℝ | *Rdoublestruck |
| U+2120 | ℠ | *servicemark |
| U+2122 | ™ | trademark |
| U+2124 | ℤ | *Zdoublestruck |
| U+2139 | ℹ | *info |
| U+220F | ∏ | product |
| U+2211 | ∑ | summation |
| U+2C64 | Ɽ | *Rtail |
| U+2C67 | Ⱨ | *Hdescender |
| U+2C68 | ⱨ | *hdescender |
| U+2C69 | Ⱪ | *Kdescender |
| U+2C6A | ⱪ | *kdescender |
| U+2C6B | Ⱬ | *Zdescender |
| U+2C6C | ⱬ | *zdescender |
| U+2C74 | ⱴ | *vcurl |
| U+2C75 | Ⱶ | Hhalf = Hclaudian |
| U+2C76 | ⱶ | hhalf = hclaudian |

I’m not sure about r-fishhook glyphs (U+027E and U+027F) and some others (U+01A6, U+01AC).

The Bold font is completely missing most of these glyphs, some are not bolded, but the ones that are also correctly have no serifs.

**Comment by khaledhosny** [comment]
I think the sans fonts contains many serifed glyphs that was there as place holders. I think the first action here would to mark them all, and make sure to drop them from the generated fonts since there presence is misleading.

I have no immediate plans to work on any missing glyphs myself, but by clearly marking them we open the way for any one interested to complete the sans fonts.

**Comment by Crissov** [comment]
I assumed the sans-serif Biolinum glyphs were generated (semi-)automatically and the routine just didn’t support hooks etc. I never tried to fix them because – loathing Font Forge’s X11 GUI – I had no access to that workflow. Also, I’m not very good at editing vector graphics like glyphs.

**Comment by khaledhosny** [comment]
Of course they were drawn manually :)

I might migrate the whole thing to a UFO workflow at some point to get rid of FontForge dependency, but it is a complex project and such a migration is unlikely to be painless.

**Comment by KrasnayaPloshchad** [comment]
Filling to #41

**Comment by khaledhosny** [comment]
Anyone is free to contribute additional glyphs.
