### ISSUE TITLE
Missing styalistic alternates for Bold

### ISSUE THREAD

**Issue by alerque** [libertinus-fonts/libertinus#47]
In working up #46, I realized there is another issue with the +salt set: none of the special shapes are available in the Bold or Bold Italic variants.

Most notably here the descender on the 'h' is missing:

```TeX
\begin[papersize=a5]{document}
\set[parameter=document.parindent,value=0]
\set[parameter=document.parskip,value=1em]
\font[family=Libertinus Serif,size=16pt]

\font[features="+salt,+ss02"]

\font[]{aâbcçdefgğhiijklmnoöpqrsştuüûvwxyz}\break
\font[style=Italic]{aâbcçdefgğhiijklmnoöpqrsştuüûvwxyz}\break
\font[weight=800]{aâbcçdefgğhiijklmnoöpqrsştuüûvwxyz}\break
\font[style=Italic,weight=800]{aâbcçdefgğhiijklmnoöpqrsştuüûvwxyz}
\end{document}
```

![selection_281](https://cloud.githubusercontent.com/assets/173595/19858822/afbb271e-9f8b-11e6-8d02-ecdef7af331e.png)

**Comment by khaledhosny** [comment]
Do you really need/use that h? I always thought it looked like some IPA/linguistics thing.

**Comment by alerque** [comment]
I do actually use it quite a bit. I'm actually rather shocked I've never seen this before given how much text I typeset with it as a defining feature. However I use it for roughly the same situation across projects and the specific situation is very rarely  bolded—often italicized but rarely bolded.

**Comment by skef** [comment]
Stylistic alternates are now uniform across all the main fonts.
