### ISSUE TITLE
Add Hebrew alef+lamed ligature (U+FB4F)

### ISSUE THREAD

**Issue by evandhall** [libertinus-fonts/libertinus#59]
I've already drawn this glyph (attached as zipped svg) and tried it out on my own system.

[uniFB4F_libertinusserif.zip](https://github.com/khaledhosny/libertinus/files/922609/uniFB4F_libertinusserif.zip)

![unifb4f_libertinusserif_example](https://cloud.githubusercontent.com/assets/3673919/25050945/6fcc814a-2107-11e7-88da-295b8a928346.png)

**Comment by khaledhosny** [comment]
Can you do the same for other styles as well?

**Comment by KrasnayaPloshchad** [comment]
Microsoft also recommened to implement `dlig` feature for this. So once this glyph is added into Libertinus Serif you can try to making it available in this way.
https://www.microsoft.com/typography/OpenTypeDev/hebrew/intro.htm#features

**Comment by khaledhosny** [comment]
Please re-open if you can contribute the ligature to all font styles.

**Comment by clsn** [comment]
Gimme a bit; I've thrown together examples for all the font styles that have Hebrew.
