### ISSUE TITLE
Combining dot above right is wrongly placed in some faces

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#65]
Copying the following string into LibreOffice, than switch to Libertinus Serif, some of them looks wrongly placed with combining dot above right, which used for presenting [Pe̍h-ōe-jī](https://en.wikipedia.org/wiki/Pe%CC%8Dh-%C5%8De-j%C4%AB), a romanization of Southern Min Chinese.
```
O͘Ó͘Ò͘Ô͘Ō͘O̍͘o͘ó͘ò͘ô͘ō͘o̍͘ 
```
![1](https://cloud.githubusercontent.com/assets/10364351/25312261/bef4df50-2847-11e7-99b2-9d63ec005d90.PNG)
Switching to Libertinus Sans will get worse effects.
![2](https://cloud.githubusercontent.com/assets/10364351/25312392/66ca235a-284a-11e7-8df3-518d55ff48c3.PNG)

Enabling OT small caps variant to them will be worse than above.

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
