### ISSUE TITLE
Combining vertical line above is wrongly placed 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#66]
Copying the string `A̍E̍I̍O̍U̍a̍e̍i̍o̍u̍` to test, than combining vertical line above looks wrongly placed in some faces other than Libertinus Serif Regular and Italic faces. Also tested with OT small caps.
![1](https://ooo.0o0.ooo/2017/04/24/58fcdd1699f0c.png)

**Comment by KrasnayaPloshchad** [comment]
These could be used for representing Hinghwa Romanization.
```
A̤̍E̤̍O̤̍Ṳ̍Ṳ̍a̤̍e̤̍o̤̍ṳ̍ṳ̍
```
![2](https://cloud.githubusercontent.com/assets/10364351/25429086/6c60dba8-2aaa-11e7-8a8e-69e4bc44c334.PNG)

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
