### ISSUE TITLE
Implement adding combining macron twice on a letter

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#67]
This combination appeared in [Kienning Colloquial Romanized Alphabet](https://en.wikipedia.org/wiki/Kienning_Colloquial_Romanized), but both Libertinus Sans and Serif have no implemention.

Coping the following strings into LibreOffice Writer:
```
Ā̄Ā̄Ā̤̄Ā̤̄Ē̄Ē̄Ē̤̄Ē̤̄Ī̄Ī̄Ō̄Ō̄Ō̤̄Ō̤̄Ū̄Ū̄Ṳ̄̄Ṳ̄̄Ṳ̄̄
ā̄ā̄ā̤̄ā̤̄ē̄ē̄ē̤̄ē̤̄ī̄ī̄ō̄ō̄ō̤̄ō̤̄ū̄ū̄ṳ̄̄ṳ̄̄ṳ̄̄ 
```
Then you’ll get the following results:
![1](https://cloud.githubusercontent.com/assets/10364351/25312556/192d0dd8-284f-11e7-863a-91342b84fb32.PNG)
![2](https://cloud.githubusercontent.com/assets/10364351/25312557/192f6ec0-284f-11e7-8949-86a6283db07b.PNG)

**Comment by KrasnayaPloshchad** [comment]
Libertinus Serif have already implemented, but not for pre-composed ā, ē, ī, ō, ū, and HarfBuzz has bad behavior when compared with Uniscribe based environment.
https://github.com/behdad/harfbuzz/issues/500

Libertinus Sans still need to implement.

**Comment by mgavioli** [comment]
@KrasnayaPloshchad :

1) in the screen shot, are all glyphs repeated twice? (in the 'ṳ̄̄' case, trice?)

2) Is the difference in how the characters are build? It seems to me that:
- the first A is:
'A' + U+0304 + U+0304
and the second:
'Amacron' + U+0304
- the first A with diaeresis below is:
'A' + U+0324 + U+0304 + U+0304
and the second is:
'Amacron' + U+0324 + U+0304

Correct? Same for the others?

3) What about the 3 'U' with diaeresis below?

**Comment by KrasnayaPloshchad** [comment]
1. Yes, macron should be looks repeated twice.
2. They are work around for an automatically converting in MediaWiki and so on, where converting combiniations into precomposed character. For example, if you input 'A' + U+0304, then it become 'Amacron' after you save it. You can try it in their [test wiki](https://test.wikipedia.org/wiki/Main_Page).
3. They are also intended working around such convertion. PS. The base letter of this combination should be U-diaerasis below.

**Comment by KrasnayaPloshchad** [comment]
@moyogo I have asked Unicode Consortium, but they refused to receive such character, they suggest using combining macron twice. Here is their reply:

>Hello... Thank you for your interest in Unicode.
>
>For this, you should use two macrons, one on top of the other. Some fonts may exhibit poor rendering, but that is a separate issue from the encoding. The correct sequence is: <0075, 0324, 0304, 0304>.
>
>Examples:
>
>Gṳ̿ing --> Gṳ̄̄ing (default font for this message)
>
>And on Windows 7, various fonts:
> 
>Gṳ̄̄ing (Times New Roman)
>Gṳ̄̄ing (Calibri)
>Gṳ̄̄ing (Georgia)
>Gṳ̄̄ing (Gentium Plus)
>Gṳ̄̄ing (Gentium Basic)
>Gṳ̄̄ing (Verdana)
>* The Gentium fonts are freely available from SIL.
>
>I hope this helps.
>
>Regards,
>    Rick

**Comment by KrasnayaPloshchad** [comment]
I have tested all those fonts as mentioned above (but not Gentium Basic), they are all works pretty, so I suggest Libertinus fonts should follow them.

**Comment by KrasnayaPloshchad** [comment]
I have tested all those fonts as mentioned above (but not Gentium Basic), they are all works pretty, so I suggest Libertinus fonts should follow them.

**Comment by mgavioli** [comment]
@khaledhosny : there is a number of issues related to diacritic placement; in addition to this one, at least https://github.com/khaledhosny/libertinus/issues/78 https://github.com/khaledhosny/libertinus/issues/70 https://github.com/khaledhosny/libertinus/issues/69 https://github.com/khaledhosny/libertinus/issues/68 https://github.com/khaledhosny/libertinus/issues/66 https://github.com/khaledhosny/libertinus/issues/65 https://github.com/khaledhosny/libertinus/issues/17 (Cyrillic) and, for Hebrew, https://github.com/khaledhosny/libertinus/issues/107 and https://github.com/khaledhosny/libertinus/issues/106 ; plus some recently closed: https://github.com/khaledhosny/libertinus/issues/118 https://github.com/khaledhosny/libertinus/issues/71 https://github.com/khaledhosny/libertinus/issues/85 and perhaps others as well not evident from their title.

The status of base/mark anchors (and their relationships with pre-composed characters) is quite inconsistent, in some fonts more than in other, but each one has its own quirks.

I see two major routes:

- **go on fixing each issue separately**, possibly with _ad hoc_ solutions, work-arounds and compromises (as I already had to do in some cases); this will presumably allow to fix a number of issues in a relatively short time, but may leave the fonts even more messy and make any additional fix harder;
- **redo the mark system from scratch**, revising pre-composed glyphs along the route, learning and borrowing from fonts known for their capabilities in this area (as several SIL fonts); this should fix a number of issues at the same time, leaving the fonts cleaner and easier to update and maintain; OTOH, it is bound to take a much longer time, it is likely to introduce differences in existing glyphs (hopefully for the better, but one never knows...) and to leave the fonts in an unstable state for a while.

Comments, anyone?

**Comment by khaledhosny** [comment]
Well, option two is the proper fix but it is quite some effort, so it is really up to the person doing the work to choose.

**Comment by KrasnayaPloshchad** [comment]
I also suggest creating a tool to check font behavior between the same codepoint and different styles.

**Comment by KrasnayaPloshchad** [comment]
CC @skef

**Comment by skef** [comment]
To the extent that I have a mental list, combining characters are not *off* it, but they're pretty far down. Not in priority, just in time order. Best to have final or final-ish glyphs before deciding where things belong above and below them. Serif-Regular and Sans-Regular are in quite good shape, some of the other faces much less so. 

Fix the fundamental combining issues and almost all of these individual cases will be solved in the process.

**Comment by khaledhosny** [comment]
Anyone is free to send pull requests that fix this.

**Comment by kopeckyf** [comment]
While looking into this I noticed that ī (Unicode 012B, Latin lowercase i with macron) currently has a custom macron which is just a bit narrower than the macron used in the combining char and in other Latin characters with macron. 

That would lead to rather awkward lay out when the ī is combined with the combining macron above as requested by OP. 

Would there be any issues in replacing the custom-width macron in ī with the usual length?
