### ISSUE TITLE
Latin letters with Combining Diaerasis Below and other diacritics are wrongly placed

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#68]
They are used in some versions of Bible and dictionaries for some dialects of Min Chinese, notably in [Fuzhou](https://en.wikipedia.org/wiki/Foochow_Romanized), [Jian’ou](https://en.wikipedia.org/wiki/Kienning_Colloquial_Romanized) and [Putian](https://en.wikipedia.org/wiki/Hinghwa_Romanized) dialets. I made a testcase for Libertinus Sans/Serif with the following strings:
```
A̤Ă̤Ā̤Á̤À̤Â̤E̤Ĕ̤Ē̤É̤È̤Ê̤O̤Ŏ̤Ó̤Ò̤Ô̤ṲṲ̆Ṳ́Ṳ̀Ṳ̂a̤ă̤ā̤á̤à̤â̤e̤ĕ̤ē̤é̤è̤ê̤o̤ŏ̤ó̤ò̤ô̤ṳṳ̆ṳ́ṳ̀ṳ̂
```
![1](https://ooo.0o0.ooo/2017/04/23/58fc818ff133d.png)
Letters with wrong mark positioning are marked in red.

**Comment by KrasnayaPloshchad** [comment]
Test again after I enabled true small caps.

![1.PNG](https://ooo.0o0.ooo/2017/04/23/58fc83f766557.png)

**Comment by KrasnayaPloshchad** [comment]
Additional test with ṳ (U+1E72/1E73)
```
Ṳ̄Ṳ̆Ṳ́Ṳ̀Ṳ̂ṳ̄ṳ̆ṳ́ṳ̀ṳ̂
```
![2](https://cloud.githubusercontent.com/assets/10364351/25428291/fcb2ee42-2aa7-11e7-8fd2-6ef9ef8ffef9.PNG)

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
