### ISSUE TITLE
Combining diacritics placings on m and n are incomplete 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#69]
They can be used for presenting syllabic consonant _m_ and _ng_ in some romanizations of Chinese dialets. Here is my test result, red letters are wrongly placed.
![1](https://ooo.0o0.ooo/2017/04/23/58fc893150078.png)

**Comment by khaledhosny** [comment]
These fonts were not designed to handle combining marks, fixing this will require an overhaul of how combining marks handled. No need to open issues for individual problems.
