### ISSUE TITLE
Bold Cyrillics Serif Italics missing

### ISSUE THREAD

**Issue by jugi1** [libertinus-fonts/libertinus#74]
Cyrillic Italics for Bold Serif Libertinus are missing.
It is also in Biolinum fonts.

Is there a way to add it?
Thanks for supporting.

**Comment by khaledhosny** [comment]
They need to be drawn of course, which is something I have no expertise in doing (drawing Cyrillic glyphs).

**Comment by kiwi0fruit** [comment]
This is very dissapoining to see that bold italic cyrilic support is in "who knows" future... I know the fast way to add them. But they would be slightly in a miss-style. The best match for Libertinus that I found is [PT Astra Serif](https://github.com/kiwi0fruit/open-mono/tree/master/Fonts). See how they fit together (**PT** means PT Astra Serif was used, **Lib** means Libertinus Serif was used):
![pt_vs_libertinus](https://user-images.githubusercontent.com/19735117/35847922-b75604f0-0b4e-11e8-94b3-e42133dcc3a0.png)

I suggest takin cyrillic italic and rest from PT Astra Serif. Maybe adjust letters height a bit. In italic style cyrillic Unicode ranges should be replaced as Libertinus Serif already has it.

That can be temporary working solution.

**Comment by kiwi0fruit** [comment]
For now the workaround is simply to have PT Astra Serif as a fallback font.

**Comment by kiwi0fruit** [comment]
@khaledhosny I suggest removing cyrillic italic from Libertinus Serif stable release (as it's of no use without bold italic). So cyrillic italic only left in dev branch or something.

When doing so we can use Libertinus Serif with any fallback font of choise (because itatic and bold italic should be from the same font for beauty and consistency).

P.S. I highly recommend PT Astra Serif as a fallback - it looks good, highly readable and really fits with Libertinus Serif.

**Comment by kiwi0fruit** [comment]
Or maybe mixing italic from Libertinus with Bold-Italic from PT Astra isn't that bad? What do you think?

**Comment by kiwi0fruit** [comment]
@khaledhosny I also suggest adding Font Forge Python script that runs before generating fonts. It iterates over characters and removes from italic, bold italic and semibold italic the characters that are not in the intersection of italic and bold italic (intersection is without semibold italic).

**Comment by kiwi0fruit** [comment]
As a temporal(?) solution I made [Libert Serif](https://github.com/kiwi0fruit/open-mono#best-serif-linux-libertine-by-philipp-h-poll) that is the same as Libertinus Serif but without cyrillic italic.

**Comment by kiwi0fruit** [comment]
Unfortunately all cyrillic fallback fonts look not enough good together with Libertinus Serif. So Libert Serif is only a temporary fix. Next attempt would be to drop semibold support and leave only bold style. Then make a slanted version of Bold regular via FontForge Python. Then take from semibold italic Vollkorn characters that should be in different style (Vollkorn is a thick font so it's semibold is closer to Libertinus Bold than it's bold). This also require taking `рдл` (and alike cyrillic symbols) from Vollkorn italic regular to Libertinus italic regular (+ adjusting their thickness and space around them to match `рдл` from Libertinus).

**Comment by kiwi0fruit** [comment]
Nope... this is also bad. The only solution is to draw them all... Or adapt manually.

**Comment by kiwi0fruit** [comment]
More Deltails: Cyrillic doesn't have bold italic. Cyrillic semibold italic is only slanted instead of real italic. PT Astra Serif (OFL) and Noto Serif/Droid Serif (Apache License v.2) [can be adapted](https://github.com/kiwi0fruit/open-fonts/tree/master/libertinus) to Libertinus Serif.

**Comment by StefanPeev** [comment]
@kiwi0fruit @khaledhosny Please, help me with your suggestions and notes and I'll do my best to draw Cyrillic Bold Italic and even the local forms for Bulgarian, Serbian and Macedonian scripts for all fonts in Libertinus family. You could see the first results at the [Gallery](https://github.com/StefanPeev/libertinus/blob/cyrillic/images/Gallery.md) and when I'm ready I'll ask you to help me to make a PR only for the final SFD file with the new and revised glyphs.

**Comment by khaledhosny** [comment]
I can’t comment on the Cyrillic design, but please see the [design guidelines](https://github.com/khaledhosny/libertinus/blob/master/documentation/Design-Guidelines.md) if they are of any help.

**Comment by StefanPeev** [comment]
@khaledhosny Thank you! Design guidelines are very good! I hope that @kiwi0fruit or @KrasnayaPloshchad could give their comments. Soon I'll be ready for PR. The working variants are already seen on [Gallery](https://github.com/StefanPeev/libertinus/blob/cyrillic/images/Gallery.md).

**Comment by StefanPeev** [comment]
[Libertinus-Cyrillic-Peev-01.pdf](https://github.com/khaledhosny/libertinus/files/1908394/Libertinus-Cyrillic-Peev-01.pdf)

**Comment by StefanPeev** [comment]
![libertinus-cyrillic-peev-01](https://user-images.githubusercontent.com/12949369/38750167-c5282c38-3f5c-11e8-851d-db9678d4ad72.png)

**Comment by kiwi0fruit** [comment]
My main idea was to adapt bold italic from PT Astra Serif - it was made by
professional Russian typeface designer.

Letterform can easily be reused because both Libertinus Serif and PT Astra
Serif are of the same size as Times New Roman.

And as I see it in your PDF example: ы, ь, ъ are better made in PT Astra
Serif. I suggest using shapes from there (even regular italic) but adjust
style - "ink dots" and serifs should match Libertinus style.

I guess some other letters should be checked... I wrote adaptation spec
somewhere above in this discussion but as you can actually draw glyphs it's
useful only for checking which letterform design is better.

сб, 14 апр. 2018, 0:52 Stefan Peev <notifications@github.com>:

**Comment by StefanPeev** [comment]
@kiwi0fruit Yes, it's true. But I just show you the moment picture of the work. I do not say the bold italic is done. There is a lot of work to be done still.

**Comment by kiwi0fruit** [comment]
That's a very good start! :)

I do not see anything more about glyph shapes for now.

сб, 14 апр. 2018, 1:24 Stefan Peev <notifications@github.com>:

**Comment by StefanPeev** [comment]
@kiwi0fruit I hope so :) I see some problems in italic version also - but I'll do not touch it. Who made the Cyrillic italic version? It's a good idea if I could contact him - especially if he/she agree we to discuss the italics.

**Comment by kiwi0fruit** [comment]
I suggest fixing problems in italic version together with adding
bold-italic (and don't actually forgetting about semibold italic). Do not
touching regular italic would lead to the worse final result and even can
add extra work of drawings bold italic twice (first now, then after fixing
regular italic). But I do not remember heavy problems... Except letter л
may be - something is wrong with it.

Cyrillic italic was drawn by Linux Libertine author. Libertinus Serif is
actually a maintained fork of LL with a bit more libre license (and more).

сб, 14 апр. 2018, 1:38 Stefan Peev <notifications@github.com>:

**Comment by StefanPeev** [comment]
@kiwi0fruit Alas there is no way to be made an interpolation between italic and bold italic with FontForge. Obviously the two styles are made absolute separately, which is not a good case - this is the reason the interpolation with FontForge to fail. I will try to prepare at least the Cyrillic version for interpolation with FontForge and thus we will have both good semibold italic version and compatable italic and bold italic version.
But it's a lot of work.

**Comment by kiwi0fruit** [comment]
I know about a lot of work. Luckily you are interested! But I think I
understand your enthusiasm (even if can't draw glyphs myself) - Libertinus
looks close enough to ideal finished result and it's beautiful.

сб, 14 апр. 2018, 2:09 Stefan Peev <notifications@github.com>:

**Comment by khaledhosny** [comment]
Fixed in ea760cc2bed4c1b8cb1a931364ff8c5d824355bd already.
