### ISSUE TITLE
Support Modifier Letter Small Capital N (U+1DB0)

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#76]
This can be used for a variant of ⁿ appeared in _Taiwan Capitol Church News_.
See: https://commons.wikimedia.org/wiki/File:Tai-Oan-Hu-Sia-Kau-Hoe-Po.jpg

**Comment by moyogo** [comment]
This looks more like a 'smcp' feature being applied than a different character: `<smallcap>Tâi-oân-hú-siâⁿ Kàu-hōe-pò</smallcap>`. I’m not saying that having U+1D3A wouldn’t be useful, just that this example is probably more relevant if you were asking for a small cap variant of U+207F. Either way, U+1D3A can probably be used for a small cap variant of U+207F.

**Comment by KrasnayaPloshchad** [comment]
Now I think this character should be ᶰ (U+1DB0), not 1D3A.

**Comment by khaledhosny** [comment]
Feel free to send a pull request.
