### ISSUE TITLE
Lots of Latin letters lacks small capital variant

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#78]
This is my test result on LibreOffice 5.3, lots of them came from Latin Extended A and B blocks, some of them are encoded in Latin Extended Additional block.
![screenshot](https://cloud.githubusercontent.com/assets/10364351/26300062/9e7d723a-3f0f-11e7-952d-73bd42bb4951.PNG)
Source file:
[Test file.zip](https://github.com/khaledhosny/libertinus/files/1018238/Test.file.zip)

**Comment by KrasnayaPloshchad** [comment]
It seems to me that this font also needs to add `pcap`/`c2pc` features.

**Comment by khaledhosny** [comment]
Feel free to send pull requests.
