### ISSUE TITLE
Missing font styles

### ISSUE THREAD

**Issue by rig8f** [libertinus-fonts/libertinus#91]
First thanks for your work on this project! Beside of math font, to have also a fully complete text font please consider implementing missing styles such as Sans bold italic and Mono variants.

**Comment by mgavioli** [comment]
IMHO, bold italic is greatly overrated, mostly in the serif area. In the majority of cases the result is 'flabby' and inconsistent, as italic (at least in the sense of cursive; oblique might be a different matter) goes in the direction of narrower and more curved design, while bold goes in the opposite direction.

Just for me, I would get rid of the Serif Bold-italic and Serif Semibold-italic too, but I agree this would be too a 'fundamentalist' approach, as they are there and nobody forces anyone to use them!

But, when a lot of details / fixes are needed on several existing fonts, spending a non-trivial amount of time to add a new Serif Bold-italic which would highly probably come out flabby (not for lack of skill, but for the inherently contrasting constrains of the italic and of the bold), would seem to me a waste of time.

This is just an opinion, of course, uses and applications may be different and perspectives may differ.

**Comment by khaledhosny** [comment]
Agreed.

**Comment by khaledhosny** [comment]
Not doing this. Any one is free to contribute additional styles, though.
